table 'Group Ownership'
	isHidden
	lineageTag: 2b6c9924-b77b-4532-b122-744b6f9deaea

	column 'Ownership Key'
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: cfa320a7-f8e3-43cc-93c7-c9c5dffbdd0e
		summarizeBy: none
		sourceColumn: Ownership Key

		annotation SummarizationSetBy = Automatic

	column 'Controlling or Non-Controlling Interest'
		dataType: string
		lineageTag: 596128d6-6f19-4b66-92a3-786a7b76b4e1
		summarizeBy: none
		sourceColumn: Controlling or Non-Controlling Interest

		annotation SummarizationSetBy = Automatic

	partition 'Group Ownership' = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Csv.Document(File.Contents(#"File Location Fixed" & "Group Ownership.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Ownership Key", Int64.Type}, {"Controlling or Non-Controlling Interest", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

