table Measures_Hidden
	isHidden
	lineageTag: 69d32931-0825-4730-91df-93293b558be0

	measure 'Net Credit Less Debit Indicator' =
			Max ( 'Account'[Account Type Indicator] ) +
			calculate(max(Account[Account Type Indicator]), USERELATIONSHIP(Layout[Income_Statement_Key],Account[Layout 2 Income Statement Key]))
		isHidden
		displayFolder: Step 02: Account type indicator
		lineageTag: aa30ee80-5788-41b6-8202-8fdd70a7a015

		changedProperty = IsHidden

	measure 'Show Value' =
			var showvalues = values(Layout[Show_Values])
			
			var hasoneshowvalue = hasonevalue(Layout[Show_Values])
			
			var result = if(hasoneshowvalue, showvalues, blank())
			return  result
		isHidden
		displayFolder: Step 07: Show Values and Blanks
		lineageTag: 722707f1-6297-452a-bb90-99a9d9ec18ad

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Credit Less Debit BASE' = ```
			VAR scenarioexternal = 
			    CALCULATE(
			        SUM( Scenario[Credit less debit] ),
			        Scenario[Scenario Key] = 1
			    )
			    
			VAR scenariointernal = 
			    CALCULATE(
			        SUM( Scenario[Credit less debit] ),
			        Scenario[Scenario Key] = 1,
			        USERELATIONSHIP( Layout[Income_Statement_Key],
			            Account[Layout 2 Income Statement Key]
			        )
			        
			    )    
			    
			        VAR Result  =  scenarioexternal+scenariointernal
			        
			        
			        RETURN Result
			```
		isHidden
		displayFolder: Step 01: Sum\_Base Calculation\Plan and Forecast\Forecast\Top Down
		lineageTag: 967a410b-ead8-4118-a6f0-72e294d8e522

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Credit Less Debit BASE' = ```
			VAR scenarioexternal = 
			    CALCULATE(
			        SUM( Scenario[Credit less debit] ),
			        Scenario[Scenario Key] = 2
			    )
			    
			VAR scenariointernal = 
			    CALCULATE(
			        SUM( Scenario[Credit less debit] ),
			        Scenario[Scenario Key] = 2,
			        USERELATIONSHIP( Layout[Income_Statement_Key],
			            Account[Layout 2 Income Statement Key]
			        )
			        
			    )    
			    
			        VAR Result  =  scenarioexternal +scenariointernal
			        
			        
			        RETURN result
			```
		isHidden
		displayFolder: Step 01: Sum\_Base Calculation\Plan and Forecast\Forecast\Bottom Up
		lineageTag: 8708698d-941a-4998-b4c2-2ddf782e54bb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Credit Less Debit BASE' = ```
			VAR scenarioexternal = 
			    CALCULATE(
			        SUM( Scenario[Credit less debit] ),
			        Scenario[Scenario Key] = 3
			    )
			    
			VAR scenariointernal = 
			    CALCULATE(
			        SUM( Scenario[Credit less debit] ),
			        Scenario[Scenario Key] = 3,
			        USERELATIONSHIP( Layout[Income_Statement_Key],
			            Account[Layout 2 Income Statement Key]
			        )
			        
			    )    
			    
			        VAR Result  =  scenarioexternal+scenariointernal
			        
			        
			        RETURN result
			```
		isHidden
		displayFolder: Step 01: Sum\_Base Calculation\Plan and Forecast\Plan
		lineageTag: 9f0dce2c-6f19-4edb-9964-c750ab754f66

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "#,##0,;(#,##0,);-" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate YTD' =
			CALCULATE(
			    [Actual Credit Less Debit @Act Fx Rate BASE]
			    , 'Effective Date'[YTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Year-to-date (YTD)
		lineageTag: 4bb93eb6-5926-40e8-bc76-37eb69706154

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG' =
			CALCULATE(
			        [Actual Credit Less Debit @Act Fx Rate BASE],
			        'Effective Date'[YTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE(
			            [Fcst BU Credit Less Debit BASE],
			            'Effective Date'[YTG] = 1
			        )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Year (CY)\At Actual Rate
		lineageTag: 357d655c-0dbe-47f8-9d64-bb5f02d8ff87

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG' =
			CALCULATE(
			        [Actual Credit Less Debit @Act Fx Rate BASE],
			        'Effective Date'[YTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE([Fcst TD Credit Less Debit BASE] , 'Effective Date'[YTG] = 1 )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Year (CY)\At Actual Rate
		lineageTag: 8e12f289-9d5a-43f6-bbe1-3b087b44893f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit @Act Fx Rate BASE' = ```
			VAR JournalEntryFactTableExternal = SUM( Ledger[Credit Less Debit @Global Fx] ) 
			
			
			VAR  JournalEntryFactTableIntneral = CALCULATE(
			    SUM( Ledger[Credit Less Debit @Global Fx] ), USERELATIONSHIP( Layout[Income_Statement_Key],
			        Account[Layout 2 Income Statement Key]
			    )
			)
			
			VAR Result  = JournalEntryFactTableExternal + JournalEntryFactTableIntneral
			
			
			RETURN Result
			```
		isHidden
		displayFolder: Step 01: Sum\_Base Calculation\Actual
		lineageTag: 7d88336c-a975-495e-b3d2-a4d0b8324b34

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "#,##0,;(#,##0,);-" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Plan Fx Rate BASE' =
			VAR JournalEntryFactTableExternal = SUM( Ledger[Credit Less Debit @plan Fx] )
			
			
			VAR  JournalEntryFactTableIntneral = CALCULATE(
			    SUM( Ledger[Credit Less Debit @plan Fx] ), USERELATIONSHIP( Layout[Income_Statement_Key],
			        Account[Layout 2 Income Statement Key]
			    )
			)
			
			VAR Result  = JournalEntryFactTableExternal + JournalEntryFactTableIntneral
			
			
			RETURN Result
		isHidden
		displayFolder: Step 01: Sum\_Base Calculation\Actual
		lineageTag: 526e9b82-fedd-46b0-ab31-1765b4ffd749

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default],  "#,##0,;(#,##0,);-")

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Fcst Fx Rate BASE' =
			VAR JournalEntryFactTableExternal = SUM( Ledger[Credit Less Debit @Fcst Fx] )
			
			
			VAR  JournalEntryFactTableIntneral = CALCULATE(
			    SUM( Ledger[Credit Less Debit @Fcst Fx] ), USERELATIONSHIP( Layout[Income_Statement_Key],
			        Account[Layout 2 Income Statement Key]
			    )
			)
			
			VAR Result  = JournalEntryFactTableExternal + JournalEntryFactTableIntneral
			
			
			RETURN Result
		isHidden
		displayFolder: Step 01: Sum\_Base Calculation\Actual
		lineageTag: 3c3af65d-7f96-45bc-a68f-b4431bf82195

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@PY Fx Rate BASE' =
			VAR JournalEntryFactTableExternal = SUM( Ledger[Credit Less Debit @PY Fx] )
			
			
			VAR  JournalEntryFactTableIntneral = CALCULATE(
			    SUM( Ledger[Credit Less Debit @PY Fx] ), USERELATIONSHIP( Layout[Income_Statement_Key],
			        Account[Layout 2 Income Statement Key]
			    )
			)
			
			VAR Result  = JournalEntryFactTableExternal + JournalEntryFactTableIntneral
			
			
			RETURN Result
		isHidden
		displayFolder: Step 01: Sum\_Base Calculation\Actual
		lineageTag: 1e057a83-846c-4d56-900b-b731f8d1da6a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG' =
			CALCULATE(
			        [Actual Credit Less Debit@PY Fx Rate BASE],
			        'Effective Date'[YTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE([Fcst TD Credit Less Debit BASE] , 'Effective Date'[YTG] = 1 )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Year (CY)\At Prior Year Rate
		lineageTag: a22a54c2-d0c8-4b12-b345-b369da713aca

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG' =
			CALCULATE(
			        [Actual Credit Less Debit@PY Fx Rate BASE],
			        'Effective Date'[YTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE(
			            [Fcst BU Credit Less Debit BASE],
			            'Effective Date'[YTG] = 1
			        )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Year (CY)\At Prior Year Rate
		lineageTag: 89e11016-6105-4f43-847b-283327fa61af

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG' =
			CALCULATE(
			        [Actual Credit Less Debit@Plan Fx Rate BASE],
			        'Effective Date'[YTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE(
			            [Fcst BU Credit Less Debit BASE],
			            'Effective Date'[YTG] = 1
			        )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Year (CY)\At Plan Rate
		lineageTag: 73ef3504-21a9-4979-a1d2-88d5b412bab4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG' =
			CALCULATE(
			        [Actual Credit Less Debit@Plan Fx Rate BASE],
			        'Effective Date'[YTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE([Fcst TD Credit Less Debit BASE] , 'Effective Date'[YTG] = 1 )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Year (CY)\At Plan Rate
		lineageTag: c2125232-c5b0-4263-b14a-fdd054c58b6b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Credit Less Debit YTD' =
			CALCULATE(
			    [Plan Credit Less Debit BASE],
			    'Effective Date'[YTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Year-to-date (YTD)\Plan
		lineageTag: d702525d-52ca-4cc8-afaa-72cf34ec3dfa

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate PYTD' =
			CALCULATE(
			    [Actual Credit Less Debit @Act Fx Rate BASE]
			    , 'Effective Date'[PYTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Year-to-date (YTD)\Prior Year-to-date (PYTD)
		lineageTag: a856f8fc-e343-4ce6-b12c-224ad66aa541

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Credit Less Debit YTD' =
			CALCULATE(
			    [Fcst TD Credit Less Debit BASE],
			    'Effective Date'[YTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Year-to-date (YTD)\Forecast
		lineageTag: 2cd6c397-156d-4f1e-8ea9-ed874fcecc97

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Credit Less Debit YTD' =
			CALCULATE(
			    [Fcst BU Credit Less Debit BASE],
			    'Effective Date'[YTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Year-to-date (YTD)\Forecast
		lineageTag: 69fa0d53-1612-46ca-ac1a-86ffb134ad2a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate PY' =
			CALCULATE(
			    [Actual Credit Less Debit @Act Fx Rate BASE]
			    , 'Effective Date'[PY] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act + Fcst\Prior Year (PY)
		lineageTag: c29027da-392f-4e7a-95da-1eac2e7e098c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Credit Less Debit CY' =
			CALCULATE(
			        [Plan Credit Less Debit BASE]
			
			    )
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act + Fcst\Current Year (CY)
		lineageTag: 39b487c6-3777-46af-b747-55dec3f41469

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@PY Fx Rate YTD' =
			CALCULATE(
			    [Actual Credit Less Debit@PY Fx Rate BASE],
			    'Effective Date'[YTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: 507c6c14-6ad5-48c5-ad1c-641b1b845391

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Fcst Fx Rate YTD' =
			CALCULATE(
			    [Actual Credit Less Debit@Fcst Fx Rate BASE],
			    'Effective Date'[YTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: 2979600b-2969-4309-bca3-60dc6f95d039

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Plan Fx Rate YTD' =
			CALCULATE(
			    [Actual Credit Less Debit@Plan Fx Rate BASE],
			    'Effective Date'[YTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: 26ab8f59-a28f-4d64-9b13-6f07872988a3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Blank rows' = ```
			//Check if account table is filtered 
			
			VAR accountinscope = 
			
			    ISFILTERED( 'Account' ) 
			
			 
			 
			
			//Check if selected calculation type equals blank 
			
			VAR selectedcalculationtype = 
			
			    SELECTEDVALUE( 
			
			        'Layout'[Calculation_type] 
			
			    ) = "Blank" 
			
			 
			 
			
			//If account table is filtered, don't show blanks else return 0 if the calculation type if blank 
			
			VAR blankrows = 
			
			    SWITCH( 
			
			        TRUE( ), 
			
			        accountinscope, BLANK( ), 
			
			        selectedcalculationtype, 0 
			
			    ) 
			
			RETURN 
			
			    blankrows
			```
		isHidden
		displayFolder: Step 07: Show Values and Blanks
		lineageTag: 7ab7bf82-5f8f-46a9-80a7-087178de1a66

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Show Value Forecast TD' = ```
			VAR showvalues = values(Layout[Show_Values])
			VAR isnotfilteredaccount = ISFILTERED(Account) = FALSE()
			//VAR isnotfilteredbusinessunit = isfiltered('Business Unit') = false()
			var isnotfilteredlegalentity = countrows('Legal Entity') =17
			var hasoneshowvalue = hasonevalue(Layout[Show_Values])
			
			var result = 
			    SWITCH(
			        TRUE(),     
			        isnotfilteredaccount  && isnotfilteredlegalentity &&hasoneshowvalue , showvalues,
			        
			        BLANK()
			    
			        
			    )        
			return  result
			```
		isHidden
		displayFolder: Step 07: Show Values and Blanks
		lineageTag: 653cddbd-b30f-4658-aee3-ee79953dcab3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure Green = "#64B669"
		isHidden
		displayFolder: Step 08: Field Paramaters\_Formatting
		lineageTag: 25b8cb73-ccfd-4a73-a952-f70631cb4177

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Blank value' = BLANK()
		isHidden
		displayFolder: Step 07: Show Values and Blanks
		lineageTag: 6e4b5035-17d6-47b6-ab92-5f6dcfd0d8c8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Show Perc' = ```
			var showperc = MAX(Layout[Show_Perc])
			    
			
			    return showperc
			```
		isHidden
		displayFolder: Step 07: Show Values and Blanks
		lineageTag: 11f2c0ce-9763-4024-9644-59a63865173e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Blank Column' = BLANK()  + BLANK()
		isHidden
		displayFolder: Step 07: Show Values and Blanks
		lineageTag: 46a72c4e-d407-4591-b39a-30dd101638d1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure Gray = "#F3F3F3"
		isHidden
		displayFolder: Step 08: Field Paramaters\_Formatting
		lineageTag: 8b2cf71d-7cd2-4dc5-b685-de250f03a7f3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure Red = "#EB3B3B"
		isHidden
		displayFolder: Step 08: Field Paramaters\_Formatting
		lineageTag: 5f3e2e9d-85d6-408f-8467-520f8834725f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure Blue = "#000000"
		isHidden
		displayFolder: Step 08: Field Paramaters\_Formatting
		lineageTag: ec641f8c-8ec0-45e8-8eeb-cc5d09bca48e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Medium Gray' = "#8b8680"
		isHidden
		displayFolder: Step 08: Field Paramaters\_Formatting
		lineageTag: 6b71589b-12d5-423d-bb17-a837c12c07f3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG' =
			CALCULATE(
			        [Actual Credit Less Debit @Act Fx Rate BASE],
			        'Effective Date'[QTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE(
			            [Fcst BU Credit Less Debit BASE],
			            'Effective Date'[QTG] = 1
			        )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Quarter (CQ)\At Actual Rate
		lineageTag: 1c983272-074a-4b31-820d-de7b0265182f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG' =
			CALCULATE(
			        [Actual Credit Less Debit @Act Fx Rate BASE],
			        'Effective Date'[QTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE([Fcst TD Credit Less Debit BASE] , 'Effective Date'[QTG] = 1 )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Quarter (CQ)\At Actual Rate
		lineageTag: 2022bf70-8315-486f-b241-6c1ac46e7a4a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG' =
			CALCULATE(
			        [Actual Credit Less Debit@Plan Fx Rate BASE],
			        'Effective Date'[QTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE(
			            [Fcst BU Credit Less Debit BASE],
			            'Effective Date'[QTG] = 1
			        )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Quarter (CQ)\At Plan Rate
		lineageTag: c75ff3d5-f0ef-4535-a891-8e299d1f8524

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG' =
			CALCULATE(
			        [Actual Credit Less Debit@Plan Fx Rate BASE],
			        'Effective Date'[QTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE([Fcst TD Credit Less Debit BASE] , 'Effective Date'[QTG] = 1 )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Quarter (CQ)\At Plan Rate
		lineageTag: bbbf5fbd-a653-44db-b506-23c56b094d4f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG' =
			CALCULATE(
			        [Actual Credit Less Debit@PY Fx Rate BASE],
			        'Effective Date'[QTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE([Fcst TD Credit Less Debit BASE] , 'Effective Date'[QTG] = 1 )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Quarter (CQ)\At Prior Year Rate
		lineageTag: 4acb0bc6-970e-4198-aaec-1e653f4762eb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG' =
			CALCULATE(
			        [Actual Credit Less Debit@PY Fx Rate BASE],
			        'Effective Date'[QTD] = 1
			    ) ///// UPDATE TO USE AGGREGATION 1
			
			        + CALCULATE(
			            [Fcst BU Credit Less Debit BASE],
			            'Effective Date'[QTG] = 1
			        )
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Current Quarter (CQ)\At Prior Year Rate
		lineageTag: f31848f3-ed15-4dc3-b38a-fb7e6de1a5b3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate QTD' =
			CALCULATE(
			    [Actual Credit Less Debit @Act Fx Rate BASE]
			    , 'Effective Date'[QTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Quarter-to-date (QTD)
		lineageTag: 343d180f-1153-46c5-8fcd-b005460e7c75

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate MTD' =
			CALCULATE(
			    [Actual Credit Less Debit @Act Fx Rate BASE]
			    , 'Effective Date'[MTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\1_Actuals\Month-to-date (MTD)
		lineageTag: 1da201cc-ed5c-407d-b5e4-b2e402a4eeaf

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Credit Less Debit CQ' =
			CALCULATE(
			        [Plan Credit Less Debit BASE],
			        'Effective Date'[CQ] = 1
			
			    )
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act + Fcst\Current Quarter (CQ)
		lineageTag: f85a007a-ad28-4864-9972-46f48978d312

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Act Fx Rate PQ' =
			CALCULATE(
			    [Actual Credit Less Debit @Act Fx Rate BASE]
			    , 'Effective Date'[PQ] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act + Fcst\Prior Quarter (PQ)
		lineageTag: a3724caa-56f7-4bb0-97fb-076dd20d9286

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Credit Less Debit QTD' =
			CALCULATE(
			    [Fcst BU Credit Less Debit BASE],
			    'Effective Date'[QTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Forecast
		lineageTag: 988a1a31-6e01-4a38-9e03-25d2e5e313b1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Credit Less Debit QTD' =
			CALCULATE(
			    [Fcst TD Credit Less Debit BASE],
			    'Effective Date'[QTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Forecast
		lineageTag: 8e930ad6-00f3-4b25-aa29-675b53213a17

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Credit Less Debit QTD' =
			CALCULATE(
			    [Plan Credit Less Debit BASE],
			    'Effective Date'[QTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Plan
		lineageTag: 06693cc2-9ea1-4cf4-bfa2-7402ed2c1683

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'PY Actual Credit Less Debit@Act Fx Rate PQTD' =
			CALCULATE(
			    [Actual Credit Less Debit @Act Fx Rate BASE]
			    , 'Effective Date'[PQTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Prior  Quarter-to-date (PQTD)
		lineageTag: a6634fcb-7042-48ac-9817-4ad158255d0a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Credit Less Debit MTD' =
			CALCULATE(
			    [Fcst BU Credit Less Debit BASE],
			    'Effective Date'[MTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Month-to-date (MTD)\Forecast
		lineageTag: 44f3c08f-5444-4c86-bdca-fcd802487c9b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Credit Less Debit MTD' =
			CALCULATE(
			    [Fcst TD Credit Less Debit BASE],
			    'Effective Date'[MTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Month-to-date (MTD)\Forecast
		lineageTag: c2995bb4-b191-409a-9a73-b7c7deb5fac4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Credit Less Debit MTD' =
			CALCULATE(
			    [Plan Credit Less Debit BASE],
			    'Effective Date'[MTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Month-to-date (MTD)\Plan
		lineageTag: 73b87b84-3590-4bfa-a310-525ba301185b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'PY Actual Credit Less Debit@Act Fx Rate PMTD' =
			CALCULATE(
			    [Actual Credit Less Debit @Act Fx Rate BASE]
			    , 'Effective Date'[PMTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\2_Comparison\Act ONLY\Month-to-date (MTD)\Prior month-to-date (PMTD)
		lineageTag: d52fb47d-7b54-4bf2-b9e8-c8b9ec684e32

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Fcst Fx Rate QTD' =
			CALCULATE(
			    [Actual Credit Less Debit@Fcst Fx Rate BASE],
			    'Effective Date'[QTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: f964f4c6-3a51-45e3-be84-a20fff854558

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Plan Fx Rate QTD' =
			CALCULATE(
			    [Actual Credit Less Debit@Plan Fx Rate BASE],
			    'Effective Date'[QTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: 0e7f1dd6-8ac5-470d-bca6-46a4b8983f80

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@PY Fx Rate QTD' =
			CALCULATE(
			    [Actual Credit Less Debit@PY Fx Rate BASE],
			    'Effective Date'[QTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: 9cd0768e-cdef-44ae-b0c0-340acaeb39bc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Fcst Fx Rate MTD' =
			CALCULATE(
			    [Actual Credit Less Debit@Fcst Fx Rate BASE],
			    'Effective Date'[MTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: ff81c723-a336-4c91-be5e-c52d806361b1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@Plan Fx Rate MTD' =
			CALCULATE(
			    [Actual Credit Less Debit@Plan Fx Rate BASE],
			    'Effective Date'[MTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 01c45700-cd96-41ce-9fff-a9b4a39660b4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Credit Less Debit@PY Fx Rate MTD' =
			CALCULATE(
			    [Actual Credit Less Debit@PY Fx Rate BASE],
			    'Effective Date'[MTD] = 1
			)
		isHidden
		displayFolder: Step 01: Sum\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 54382e87-bc9a-45d5-af8d-e8cb9088f031

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate YTD' = [Actual Credit Less Debit@Act Fx Rate YTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Year-to-date (YTD)
		lineageTag: e29e62fe-54bb-493d-9d1f-1b0b837b115b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG' = [Actual Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Year (CY)\At Actual Rate
		lineageTag: 6de1249e-a744-48a3-a93a-6fffa27da809

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG' = [Actual Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Year (CY)\At Actual Rate
		lineageTag: bfcb8de2-52b6-4a25-83d0-3d8cdbddb639

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG' =
			[Actual Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG]
			* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Year (CY)\At Prior Year Rate
		lineageTag: 7be24c1f-0d83-4cad-b006-17d14e976ad0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG' = [Actual Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Year (CY)\At Prior Year Rate
		lineageTag: 72ca2789-9291-4339-93f5-53b4b04bb74d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG' = [Actual Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Year (CY)\At Plan Rate
		lineageTag: 536ad5d4-5e7e-4059-aa0a-398a68ec71f0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG' = [Actual Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Year (CY)\At Plan Rate
		lineageTag: 6a8100f6-a02d-4285-a24d-7fd21fdcfe0a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG' = [Actual Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Quarter (CQ)\At Actual Rate
		lineageTag: d614c2ad-6bde-42ca-9da3-9be566cad541

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG' = [Actual Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Quarter (CQ)\At Actual Rate
		lineageTag: 14347d55-3493-4770-92dc-2a633deb29dc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG' = [Actual Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Quarter (CQ)\At Plan Rate
		lineageTag: a8240eb1-3f4f-4bec-8b13-2dab46a9205f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG' = [Actual Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Quarter (CQ)\At Plan Rate
		lineageTag: 8e07f93c-b21d-48d9-b492-d80adf1453d7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG' = [Actual Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Quarter (CQ)\At Prior Year Rate
		lineageTag: b3f8c5a0-6404-428f-8136-3f7c0cc04514

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG' = [Actual Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Current Quarter (CQ)\At Prior Year Rate
		lineageTag: 0b4ec5e4-f0a7-4a9b-9e8b-edbea7c1708f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate QTD' = [Actual Credit Less Debit@Act Fx Rate QTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Quarter-to-date (QTD)
		lineageTag: d3fa526b-362b-4593-a3a2-3a4db4596ab7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate MTD' = [Actual Credit Less Debit@Act Fx Rate MTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\1_Actuals\Month-to-date (MTD)
		lineageTag: 36c3e039-ffc8-4c45-b21c-4da3b334bbc5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Line-Item Credit Less Debit YTD' = [Plan Credit Less Debit YTD]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Year-to-date (YTD)\Plan
		lineageTag: aaefd5f9-0f47-429d-b39a-e2432182c267

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate PYTD' = [Actual Credit Less Debit@Act Fx Rate PYTD]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Year-to-date (YTD)\Prior Year-to-date (PYTD)
		lineageTag: 3dfaa9cb-7cc0-415e-84bf-848100eead17

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Line-Item Credit Less Debit YTD' = [Fcst TD Credit Less Debit YTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Year-to-date (YTD)\Forecast
		lineageTag: 17641af9-801d-4b8f-a13f-af4a4408e7e7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Line-Item Credit Less Debit YTD' = [Fcst BU Credit Less Debit YTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Year-to-date (YTD)\Forecast
		lineageTag: 72fe5c7a-eeeb-402d-9451-ccffd23f63ea

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Line-Item Credit Less Debit QTD' = [Fcst BU Credit Less Debit QTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Forecast
		lineageTag: ea4842a8-9990-4e1b-bbd8-8eef50a84106

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Line-Item Credit Less Debit QTD' = [Fcst TD Credit Less Debit QTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Forecast
		lineageTag: b0aac867-5fd4-4160-ba50-4d5fe2259055

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Line-Item Credit Less Debit QTD' = [Plan Credit Less Debit QTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Plan
		lineageTag: fe97a2e1-dff7-4a70-b9f4-4d589569ffd0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate PQTD' = [PY Actual Credit Less Debit@Act Fx Rate PQTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Prior  Quarter-to-date (PQTD)
		lineageTag: 06e0fdfb-ff58-44e5-9a1b-47dced2fcbf6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Line-Item Credit Less Debit MTD' = [Fcst BU Credit Less Debit MTD]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Month-to-date (MTD)\Forecast
		lineageTag: 3fdcec88-3363-4876-b23c-ea5e8c6ef53a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Line-Item Credit Less Debit MTD' = [Fcst TD Credit Less Debit MTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Month-to-date (MTD)\Forecast
		lineageTag: 63d229ab-220a-433a-8ef0-c184f279ac47

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Line-Item Credit Less Debit MTD' = [Plan Credit Less Debit MTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Month-to-date (MTD)\Plan
		lineageTag: 4dc07248-7f0a-4066-b5a3-6ecad8811751

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate PMTD' = [PY Actual Credit Less Debit@Act Fx Rate PMTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act ONLY\Month-to-date (MTD)\Prior month-to-date (PMTD)
		lineageTag: 41ed0320-f85e-43c1-ae88-eab1da9dd7a0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate PY' = [Actual Credit Less Debit@Act Fx Rate PY] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act + Fcst\Prior Year (PY)
		lineageTag: 5ee5bbd6-39e3-46e5-8d6f-747f3cd4e23d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Line-Item Credit Less Debit CY' = [Plan Credit Less Debit CY] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act + Fcst\Current Year (CY)
		lineageTag: cc761d9b-645c-42cb-8370-6a25c1fcb717

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Line-Item Credit Less Debit CQ' = [Plan Credit Less Debit CQ] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act + Fcst\Current Quarter (CQ)
		lineageTag: ea7758f8-94c1-41d3-adc0-d9e1b6fe9f14

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Act Fx Rate PQ' = [Actual Credit Less Debit@Act Fx Rate PQ]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\2_Comparison\Act + Fcst\Prior Quarter (PQ)
		lineageTag: 36bb5a83-3d89-4fee-a227-6d8f44bd5d11

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@PY Fx Rate YTD' = [Actual Credit Less Debit@PY Fx Rate YTD]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: c645a22c-cc5f-4b39-b552-11c4450f307f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Fcst Fx Rate YTD' = [Actual Credit Less Debit@Fcst Fx Rate YTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: 5bcc08cc-bb14-4e09-902c-33161ea1a54a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Plan Fx Rate YTD' = [Actual Credit Less Debit@Plan Fx Rate YTD]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: 67494909-49e4-49a6-be4c-d97e45d6c1b3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Fcst Fx Rate QTD' = [Actual Credit Less Debit@Fcst Fx Rate QTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: d9cb372a-c664-4661-8537-1c8307a978b7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Plan Fx Rate QTD' = [Actual Credit Less Debit@Plan Fx Rate QTD]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: 76747300-d931-41de-bd63-c80ab9d8ff8d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@PY Fx Rate QTD' = [Actual Credit Less Debit@PY Fx Rate QTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: 3477e803-7e4d-4b24-b4de-55f9565ae2fa

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Fcst Fx Rate MTD' = [Actual Credit Less Debit@Fcst Fx Rate MTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 1da36237-d2ce-43f5-813d-2105908745c7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@Plan Fx Rate MTD' = [Actual Credit Less Debit@Plan Fx Rate MTD]* [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 4add0c52-5d85-476f-b66b-554dfb9f2fe6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Line-Item Credit Less Debit@PY Fx Rate MTD' = [Actual Credit Less Debit@PY Fx Rate MTD] * [Net Credit Less Debit Indicator]
		isHidden
		displayFolder: Step 03: Line-item\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 2ec92cd5-ab1c-4577-ae07-8b3ec3b9c859

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate YTD' = ```
			// Part 1 
			
			VAR NCLD_filter_context_calculated_table =  
			    CALCULATETABLE( 
			        'Layout', 
			        REMOVEFILTERS( 'Layout' ), 
			        'Layout'[Income_Statement_Key] 
			            >= MIN( 
			                'Layout'[Subtotal_from] 
			            ), 
			        'Layout'[Income_Statement_Key] 
			            <= MIN( 
			                'Layout'[Subtotal_To] 
			            )     ) 
			
			 
			
			// Part 2 
			
			VAR result = 
			    CALCULATE( 
			        [Actual Line-item Credit Less Debit@Act Fx Rate YTD],  
			              NCLD_filter_context_calculated_table 
			    ) 
			 
			// Part 3 
			
			
			RETURN 
			
			    result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Year-to-date (YTD)
		lineageTag: ced4522f-f0dd-4c44-a533-152fa78f8a94

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG' = ```
			VAR NCLD_filter_context_calculated_table =  
			    CALCULATETABLE( 
			        'Layout', 
			        REMOVEFILTERS( 'Layout' ), 
			        'Layout'[Income_Statement_Key] 
			            >= MIN( 
			                'Layout'[Subtotal_from] 
			            ), 
			        'Layout'[Income_Statement_Key] 
			            <= MIN( 
			                'Layout'[Subtotal_To] 
			            )     ) 
			
			 
			
			// Part 2 
			
			VAR result = 
			    CALCULATE( 
			        [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,  
			              NCLD_filter_context_calculated_table 
			    ) 
			 
			// Part 3 
			
			
			RETURN 
			
			    result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Year (CY)\At Actual Rate
		lineageTag: c59ac2f8-99ed-4654-9f52-cc7a554c6489

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Year (CY)\At Actual Rate
		lineageTag: a6a3e20a-3850-4b4c-9311-3510ef317363

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Year (CY)\At Prior Year Rate
		lineageTag: 81d97dce-dea9-486c-832e-fbe8e7a33f77

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Year (CY)\At Prior Year Rate
		lineageTag: 667d5350-64c9-49a7-a178-25ec879686cd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Year (CY)\At Plan Rate
		lineageTag: 87695849-3ca0-492e-9f00-fbd5c4dc1b07

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Year (CY)\At Plan Rate
		lineageTag: 51c0f7cd-9046-49a0-b3d9-d3ed5ded52bc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Quarter (CQ)\At Actual Rate
		lineageTag: 0fcbfc46-4de7-48b7-8d94-1bb901d3ecbd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Quarter (CQ)\At Actual Rate
		lineageTag: 99b5962f-c278-4c96-9c79-b0221be1fcf6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Quarter (CQ)\At Plan Rate
		lineageTag: e2f946fc-0192-4519-b0f5-02499b7e228c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Quarter (CQ)\At Plan Rate
		lineageTag: 6ca960f0-f1a6-4bbd-921d-303b01297aee

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Quarter (CQ)\At Prior Year Rate
		lineageTag: 1600e66b-1ee3-4496-ae58-19812954adc6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Current Quarter (CQ)\At Prior Year Rate
		lineageTag: 896ebf9b-b12b-43e5-bf1f-8efcf15b0258

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate QTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			            [Actual Line-Item Credit Less Debit@Act Fx Rate QTD]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Quarter-to-date (QTD)
		lineageTag: 6d9e220a-08f2-4a86-8764-2e41c6fc5bb2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate MTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			           [Actual Line-Item Credit Less Debit@Act Fx Rate MTD]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\1_Actuals\Month-to-date (MTD)
		lineageTag: da0951fe-e20f-4ac0-93c9-885606ecdad2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Subtotal Credit Less Debit YTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			          [Plan Line-Item Credit Less Debit YTD]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Year-to-date (YTD)\Plan
		lineageTag: 0af0bd74-d665-44a9-a3e0-2b8fe032e5ec

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate PYTD' = ```
			VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			          [Actual Line-Item Credit Less Debit@Act Fx Rate PYTD]  ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Year-to-date (YTD)\Prior Year-to-date (PYTD)
		lineageTag: e5d259d3-8074-4b4e-8443-bf6ddd9f07ac

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Subtotal Credit Less Debit YTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Fcst TD Line-Item Credit Less Debit YTD] ,  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Year-to-date (YTD)\Forecast
		lineageTag: 511e62eb-7d9a-4ecc-9eb7-668a32b01ae9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Subtotal Credit Less Debit YTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Fcst BU Line-Item Credit Less Debit YTD],  
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Year-to-date (YTD)\Forecast
		lineageTag: b89bbe2c-c0f8-484e-865a-bbfad1c3c7be

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Subtotal Credit Less Debit QTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Fcst BU Line-Item Credit Less Debit QTD]   ,
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Forecast
		lineageTag: 6fadefb1-db8f-49e2-af74-19e0063dfce5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Subtotal Credit Less Debit QTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Fcst TD Line-Item Credit Less Debit QTD], 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Forecast
		lineageTag: e05d3a9d-4d03-4bab-87c4-d8a0d710c845

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Subtotal Credit Less Debit QTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Plan Line-Item Credit Less Debit QTD] , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Plan
		lineageTag: 873fd6c6-f65f-45b9-a91f-27b1ebb65b95

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate PQTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Actual Line-Item Credit Less Debit@Act Fx Rate PQTD] , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Prior  Quarter-to-date (PQTD)
		lineageTag: 2ee64b7a-e21e-4af7-b490-b349353008f9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Subtotal Credit Less Debit MTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Fcst BU Line-Item Credit Less Debit MTD]  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Month-to-date (MTD)\Forecast
		lineageTag: bbbacccd-06a9-486d-ab7d-27849ee1e858

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Subtotal Credit Less Debit MTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Fcst TD Line-Item Credit Less Debit MTD]  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Month-to-date (MTD)\Forecast
		lineageTag: 122f1a57-fa1c-4992-be45-2f4ce9bea2e3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Subtotal Credit Less Debit MTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Plan Line-Item Credit Less Debit MTD] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Month-to-date (MTD)\Plan
		lineageTag: 1728bdab-680f-4cde-b074-4b9cb5c06f1d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate PMTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act ONLY\Month-to-date (MTD)\Prior month-to-date (PMTD)
		lineageTag: 832ccc40-f887-467e-9ea0-81b90b72ed8f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate PY' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Actual Line-Item Credit Less Debit@Act Fx Rate PY] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act + Fcst\Prior Year (PY)
		lineageTag: ea027d1a-7862-4aea-8058-5a651297cea5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Subtotal Credit Less Debit CY' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Plan Line-Item Credit Less Debit CY] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act + Fcst\Current Year (CY)
		lineageTag: 7cc05040-87c5-49d2-997c-a1765cf4133b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Subtotal Credit Less Debit CQ' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			         [Plan Line-Item Credit Less Debit CQ] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act + Fcst\Current Quarter (CQ)
		lineageTag: 1b945838-ac54-4443-8d74-ee7d8f7f8215

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Act Fx Rate PQ' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			        [Actual Line-Item Credit Less Debit@Act Fx Rate PQ] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\2_Comparison\Act + Fcst\Prior Quarter (PQ)
		lineageTag: adb38c71-3f64-438b-a9f7-c0fac8e4b693

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@PY Fx Rate YTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			        [Actual Line-Item Credit Less Debit@PY Fx Rate YTD] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: 247febed-41d2-4518-832d-028aef394b6c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Fcst Fx Rate YTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			        [Actual Line-Item Credit Less Debit@Fcst Fx Rate YTD] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: ecf38235-d1ab-4cde-9585-951a7e4e8a2b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Plan Fx Rate YTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			        [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD]
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: d13af4fd-6f02-4d18-b021-053ec206b8f0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Fcst Fx Rate QTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			        [Actual Line-Item Credit Less Debit@Fcst Fx Rate QTD] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: 635597ba-52a9-4f19-9426-e2a308454d75

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Plan Fx Rate QTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			       [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD]
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: ad01fbf9-d54c-437c-ac22-dcb00de6f83a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@PY Fx Rate QTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			       [Actual Line-Item Credit Less Debit@PY Fx Rate QTD]
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: 85e6ab5b-5fc1-459a-a7d1-07c2d0cdbb11

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Fcst Fx Rate MTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			       [Actual Line-Item Credit Less Debit@Fcst Fx Rate MTD] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 3f16e686-73bd-4bc7-bd8e-6965be5cfdbb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@Plan Fx Rate MTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			       [Actual Line-Item Credit Less Debit@Plan Fx Rate MTD] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 98c46ab1-abdb-4d38-bae7-000cbeffa6ec

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Subtotal Credit Less Debit@PY Fx Rate MTD' = ```
			 VAR NCLD_filter_context_calculated_table =  
			        CALCULATETABLE( 
			            'Layout', 
			            REMOVEFILTERS( 'Layout' ), 
			            'Layout'[Income_Statement_Key] 
			                >= MIN( 
			                    'Layout'[Subtotal_from] 
			                ), 
			            'Layout'[Income_Statement_Key] 
			                <= MIN( 
			                    'Layout'[Subtotal_To] 
			                )     ) 
			    
			     
			    
			    // Part 2 
			    
			    VAR result = 
			        CALCULATE( 
			       [Actual Line-Item Credit Less Debit@PY Fx Rate MTD] 
			  , 
			                  NCLD_filter_context_calculated_table 
			        ) 
			     
			    // Part 3 
			    
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 04: Subtotal\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 1d9cc5b2-efb8-49b8-a472-2cf49da32e66

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other@Base Caculations' =
			VAR Isaccountordatefiltered = IF( OR( ISFILTERED( Account ), ISFILTERED( 'Effective Date'[Fiscal Date] ) ), BLANK( ), 1 )
			
			
			
			    // Part 2: Determines the layout calculation type
			
			    VAR SelectedCalcualtionType = SELECTEDVALUE( Layout[Calculation_type] )
			
			
			
			    // Part 3: Determines which Time Period selected
			
			    VAR SelectedTimePeriod =
			        SELECTEDVALUE(
			            'Effective Date'[Fiscal Year-Period],
			            SELECTEDVALUE(
			                'Effective Date'[Fiscal Year-Quarter],
			                CONVERT( SELECTEDVALUE( 'Effective Date'[Fiscal Year] ), STRING )
			            )
			        )
			
			
			
			    // Part 4: Filter the other non-generel ledger information table down to calculation type  // and the time period in scope
			
			    VAR CalculateTableOtherNonGeneralLedgerInformation =
			        CALCULATETABLE(
			            'Other Non General Ledger Information',
			            'Other Non General Ledger Information'[Calculation type] = SelectedCalcualtionType,
			            'Other Non General Ledger Information'[Time period] = SelectedTimePeriod
			        )
			
			
			
			    // Part 5: Sum the value of the filtered table in part 4 and return blank if The accounts table is in scope
			
			    VAR result =
			        CALCULATE( SUM( 'Other Non General Ledger Information'[Value] ), CalculateTableOtherNonGeneralLedgerInformation )
			            * Isaccountordatefiltered
			
			
			
			    // Part 6: Return to result
			
			    RETURN
			        result
		isHidden
		displayFolder: Step 05: Other\_Base calculations
		lineageTag: 35978b1e-4808-4f08-80be-f2787c0bc965

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other YTD' = CALCULATE([Actual Other@Base Caculations TD], 'Effective Date'[YTD] = 1)
		isHidden
		displayFolder: Step 05: Other\1_Actuals\Year-to-date (YTD)
		lineageTag: eaa625d7-dbaa-4bbd-9844-ee3e503fad28

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other QTD' = CALCULATE([Actual Other@Base Caculations TD], 'Effective Date'[QTD] = 1)
		isHidden
		displayFolder: Step 05: Other\1_Actuals\Quarter-to-date (QTD)
		lineageTag: c0040ec2-cff4-4fe3-b3c3-ff7f4e317ecf

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other MTD' = CALCULATE([Actual Other@Base Caculations], 'Effective Date'[MTD] = 1)
		isHidden
		displayFolder: Step 05: Other\1_Actuals\Month-to-date (MTD)
		lineageTag: b0205d67-0250-428b-8b6f-b9994b41e9b1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other CY' = CALCULATE([Actual Other@Base Caculations], 'Effective Date'[CY] = 1)
		isHidden
		displayFolder: Step 05: Other\1_Actuals\Current Year (CY)
		lineageTag: 3f9cf55b-c902-42ed-b701-7898ca1573b2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other CQ' = CALCULATE([Actual Other@Base Caculations], 'Effective Date'[CQ] = 1)
		isHidden
		displayFolder: Step 05: Other\1_Actuals\Current Quarter (CQ)
		lineageTag: 026c6a58-fae5-4763-8540-eabc75d62093

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			           [Actual Line-item Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG]   +  
			    
			           [Actual Subtotal Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG]  +  
			    
			            [Actual Other CQ], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			    [Actual Line-item Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG]   +  
			    
			           [Actual Subtotal Credit Less Debit@Act Fx Rate QTD + Fcst BU Credit Less Debit QTG]  +  
			    
			            [Actual Other CQ], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Quarter (CQ)\At Actual Rate
		lineageTag: d17de3ea-d98b-4a20-8886-029d795d9782

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			           [Actual Line-Item Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG]    +  
			    
			            [Actual Subtotal Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG]   +  
			    
			            [Actual Other CQ], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			          [Actual Line-Item Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG]    +  
			    
			            [Actual Subtotal Credit Less Debit@Act Fx Rate QTD + Fcst TD Credit Less Debit QTG]   +  
			    
			            [Actual Other CQ], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Quarter (CQ)\At Actual Rate
		lineageTag: 5c4909c1-6404-49b9-97bb-f52340589c1b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			           [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG]   +  
			    
			            [Actual Subtotal Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG]  +  
			    
			            [Actual Other CQ], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			             [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG]   +  
			    
			            [Actual Subtotal Credit Less Debit@Plan Fx Rate QTD + Fcst BU Credit Less Debit QTG]  +  
			    
			            [Actual Other CQ], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Quarter (CQ)\At Plan Rate
		lineageTag: b6ff54e3-a46a-462a-9232-757564a82c17

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG]   +  
			    
			            [Actual Subtotal Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG]   +  
			        
			            [Actual Other CQ], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			        [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG]   +  
			    
			            [Actual Subtotal Credit Less Debit@Plan Fx Rate QTD + Fcst TD Credit Less Debit QTG]   +  
			        
			            [Actual Other CQ], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Quarter (CQ)\At Plan Rate
		lineageTag: d76ac338-e62f-4376-b6ed-b5871f458d00

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG' = ```
			    // Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Actual Line-Item Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG]   +  
			        
			                [Actual Subtotal Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG]    +  
			            
			                [Actual Other CQ], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			 
			              [Actual Line-Item Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG]   +  
			        
			                [Actual Subtotal Credit Less Debit@PY Fx Rate QTD + Fcst TD Credit Less Debit QTG]    +  
			            
			                [Actual Other CQ], 
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Quarter (CQ)\At Prior Year Rate
		lineageTag: 9b224c9f-7630-4bc3-89d5-7addf33f181e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG' = ```
			    // Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Actual Line-Item Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG]  +  
			        
			                [Actual Subtotal Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG]    +  
			            
			                [Actual Other CQ], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			 
			               [Actual Line-Item Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG]  +  
			        
			                [Actual Subtotal Credit Less Debit@PY Fx Rate QTD + Fcst BU Credit Less Debit QTG]    +  
			            
			                [Actual Other CQ], 
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Quarter (CQ)\At Prior Year Rate
		lineageTag: 9e2fdb97-0d82-4bbf-a29a-918841ecc98e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			               [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			               [Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] +  
			        
			                [Actual Other CY], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			       [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			               [Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] +  
			        
			                [Actual Other CY], 
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Year (CY)\At Actual Rate
		lineageTag: e6e4f4d3-3220-49f9-a45d-b3e7d5b30821

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			               [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] +  
			        
			               [Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] +  
			        
			                [Actual Other CY], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			       
			               [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] +  
			        
			               [Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] +  
			        
			                [Actual Other CY], 
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Year (CY)\At Actual Rate
		lineageTag: 649d2063-b035-426b-9940-37f544f3f780

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			               [Actual Line-Item Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG] +  
			        
			              [Actual Subtotal Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG] +  
			        
			                [Actual Other CY], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			       
			             [Actual Line-Item Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG] +  
			        
			              [Actual Subtotal Credit Less Debit@PY Fx Rate YTD + Fcst TD Credit Less Debit YTG] +  
			        
			                [Actual Other CY], 
			        
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Year (CY)\At Prior Year Rate
		lineageTag: 6d6bdc58-2129-4b4b-ab32-7dcf2fff5ab5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Actual Line-Item Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			             [Actual Subtotal Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			                [Actual Other CY], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			       
			           [Actual Line-Item Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			             [Actual Subtotal Credit Less Debit@PY Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			                [Actual Other CY], 
			        
			        
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Year (CY)\At Prior Year Rate
		lineageTag: 669b076a-b481-414d-a9b2-1e5f646ceee8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			             [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			            [Actual Subtotal Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			                [Actual Other CY], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			       
			           [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			            [Actual Subtotal Credit Less Debit@Plan Fx Rate YTD + Fcst BU Credit Less Debit YTG]  +  
			        
			                [Actual Other CY], 
			        
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Year (CY)\At Plan Rate
		lineageTag: 0ca54716-70f3-4976-84e0-47fda9fe3337

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			            [Actual line-item Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG]  +  
			        
			            [Actual subtotal Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG]   +  
			        
			                [Actual Other CY], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			          [Actual line-item Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG]  +  
			        
			            [Actual subtotal Credit Less Debit@Plan Fx Rate YTD + Fcst TD Credit Less Debit YTG]   +  
			        
			                [Actual Other CY], 
			        
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Current Year (CY)\At Plan Rate
		lineageTag: bd69df75-c748-4bb2-9f26-6203247d139d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate MTD' = ```
			  // Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Actual Line-Item Credit Less Debit@Act Fx Rate MTD]  +  
			    
			         [Actual subtotal Credit Less Debit@Act Fx Rate MTD] +  
			    
			            [Actual Other MTD], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			     [Actual Line-Item Credit Less Debit@Act Fx Rate MTD]  +  
			    
			         [Actual subtotal Credit Less Debit@Act Fx Rate MTD] +  
			    
			            [Actual Other MTD], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Month-to-date (MTD)
		lineageTag: 9699326d-f41c-4fac-bb8c-2541e7bc7a14

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate QTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Actual Line-Item Credit Less Debit@Act Fx Rate QTD]   +  
			        
			             [Actual Subtotal Credit Less Debit@Act Fx Rate QTD]  +  
			        
			                [Actual Other QTD], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        [Actual Line-Item Credit Less Debit@Act Fx Rate QTD]   +  
			        
			             [Actual Subtotal Credit Less Debit@Act Fx Rate QTD]  +  
			        
			                [Actual Other QTD], 
			        
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Quarter-to-date (QTD)
		lineageTag: 874c0a2a-4e84-441b-ab6e-28515ce282fe

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate YTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Actual Line-Item Credit Less Debit@Act Fx Rate YTD]  +  
			        
			             [Actual Subtotal Credit Less Debit@Act Fx Rate YTD] +  
			        
			                [Actual Other YTD], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			     [Actual Line-Item Credit Less Debit@Act Fx Rate YTD]  +  
			        
			             [Actual Subtotal Credit Less Debit@Act Fx Rate YTD] +  
			        
			                [Actual Other YTD], 
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\1_Actuals\Year-to-date (YTD)
		lineageTag: 5c23ee51-1214-4c3b-8305-561db8a133ae

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other PY' = CALCULATE([Actual Other@Base Caculations], 'Effective Date'[PY] = 1)
		isHidden
		displayFolder: Step 05: Other\2_Comparison\Act + Fcst\Prior Year (PY)
		lineageTag: aaa02e3b-6f09-42fb-85da-3ff04a6e2552

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other PQ' = CALCULATE([Actual Other@Base Caculations], 'Effective Date'[PQ] = 1)
		isHidden
		displayFolder: Step 05: Other\2_Comparison\Act + Fcst\Prior Quarter (PQ)
		lineageTag: 874eae1e-6fdb-460d-bd9c-8165206c4c50

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Divide Credit Less Debit CQ' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Plan Line-Item Credit Less Debit CQ]   +  
			    
			           [Plan Subtotal Credit Less Debit CQ]  +  
			    
			            [Actual Other CQ], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			       [Plan Line-Item Credit Less Debit CQ]   +  
			    
			           [Plan Subtotal Credit Less Debit CQ]  +  
			    
			            [Actual Other CQ], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act + Fcst\Current Quarter (CQ)
		lineageTag: 6e6f7b46-5066-4d52-9cb5-30378944a875

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Divide Credit Less Debit CY' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Plan Line-Item Credit Less Debit CY]   +  
			    
			           [Plan Subtotal Credit Less Debit CY]  +  
			    
			            [Actual Other CY], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			           [Plan Line-Item Credit Less Debit CY]   +  
			    
			           [Plan Subtotal Credit Less Debit CY]  +  
			    
			            [Actual Other CY], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act + Fcst\Current Year (CY)
		lineageTag: 2eab5373-4e53-480a-b694-339d5a6aced3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate PQ' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Actual Line-Item Credit Less Debit@Act Fx Rate PQ]   +  
			    
			          [Actual Subtotal Credit Less Debit@Act Fx Rate PQ]  +  
			    
			            [Actual Other PQ], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			              [Actual Line-Item Credit Less Debit@Act Fx Rate PQ]   +  
			    
			          [Actual Subtotal Credit Less Debit@Act Fx Rate PQ]  +  
			    
			            [Actual Other PQ], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act + Fcst\Prior Quarter (PQ)
		lineageTag: 944cce5c-677c-48f5-882e-130d57ad9bc9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate PY' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Actual Line-Item Credit Less Debit@Act Fx Rate PY]   +  
			    
			          [Actual Subtotal Credit Less Debit@Act Fx Rate PY]   +  
			    
			            [Actual Other PY], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			                 [Actual Line-Item Credit Less Debit@Act Fx Rate PY]   +  
			    
			          [Actual Subtotal Credit Less Debit@Act Fx Rate PY]   +  
			    
			            [Actual Other PY], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act + Fcst\Prior Year (PY)
		lineageTag: 2a4124c8-5ac8-4d5e-9af9-96542148aa50

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Divide Credit Less Debit MTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Fcst BU Line-Item Credit Less Debit MTD]    +  
			    
			           [Fcst BU Subtotal Credit Less Debit MTD]  +  
			    
			            [Actual Other MTD], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			              [Fcst BU Line-Item Credit Less Debit MTD]    +  
			    
			           [Fcst BU Subtotal Credit Less Debit MTD]  +  
			    
			            [Actual Other MTD], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Month-to-date (MTD)\Forecast
		lineageTag: be575dad-19de-42b4-a1c9-b4dbceb4e5d2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Divide Credit Less Debit MTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Fcst TD Line-Item Credit Less Debit MTD]    +  
			    
			           [Fcst TD Subtotal Credit Less Debit MTD]   +  
			    
			            [Actual Other MTD], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			           [Fcst TD Line-Item Credit Less Debit MTD]    +  
			    
			           [Fcst TD Subtotal Credit Less Debit MTD]   +  
			    
			            [Actual Other MTD], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Month-to-date (MTD)\Forecast
		lineageTag: c77f1396-d511-4e9c-b125-8f234171b57e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Divide Credit Less Debit MTD' = ```
			 // Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Plan Line-Item Credit Less Debit MTD]    +  
			        
			               [Plan Subtotal Credit Less Debit MTD]    +  
			        
			                [Actual Other MTD], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			          [Plan Line-Item Credit Less Debit MTD]    +  
			        
			               [Plan Subtotal Credit Less Debit MTD]    +  
			        
			                [Actual Other MTD], 
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Month-to-date (MTD)\Plan
		lineageTag: 041f8b34-9396-4e29-9aae-8da2cd3b9fb9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate PMTD' = ```
			 // Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD]   +  
			        
			              [Actual Subtotal Credit Less Debit@Act Fx Rate PMTD]   +  
			        
			                [Actual Other MTD], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			            [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD]   +  
			        
			              [Actual Subtotal Credit Less Debit@Act Fx Rate PMTD]   +  
			        
			                [Actual Other MTD], 
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Month-to-date (MTD)\Prior month-to-date (PMTD)
		lineageTag: 1e0466e9-a793-4941-aba4-e24d8a166c12

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Divide Credit Less Debit QTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Fcst BU Line-Item Credit Less Debit QTD]    +  
			    
			           [Fcst BU Subtotal Credit Less Debit QTD]  +  
			    
			            [Actual Other QTD], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			              [Fcst BU Line-Item Credit Less Debit QTD]    +  
			    
			           [Fcst BU Subtotal Credit Less Debit QTD]  +  
			    
			            [Actual Other QTD], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Forecast
		lineageTag: 8b89b9bb-ff0d-4874-b2b9-da7d57bb6b1e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Divide Credit Less Debit QTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Fcst TD Line-Item Credit Less Debit QTD]    +  
			    
			           [Fcst TD Subtotal Credit Less Debit QTD]   +  
			    
			            [Actual Other QTD], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			           [Fcst TD Line-Item Credit Less Debit QTD]    +  
			    
			           [Fcst TD Subtotal Credit Less Debit QTD]   +  
			    
			            [Actual Other QTD], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Forecast
		lineageTag: 382ac47c-a6eb-405e-9c0e-d92fb70fe3fd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Divide Credit Less Debit QTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Plan Line-Item Credit Less Debit QTD]    +  
			        
			               [Plan Subtotal Credit Less Debit QTD]    +  
			        
			                [Actual Other QTD], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			          [Plan Line-Item Credit Less Debit QTD]    +  
			        
			               [Plan Subtotal Credit Less Debit QTD]    +  
			        
			                [Actual Other QTD], 
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Plan
		lineageTag: 232332ff-f28e-4313-b448-7cf4e58ea917

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate PQTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Actual Line-Item Credit Less Debit@Act Fx Rate PQTD]   +  
			        
			              [Actual Subtotal Credit Less Debit@Act Fx Rate PQTD]   +  
			        
			                [Actual Other QTD], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			            [Actual Line-Item Credit Less Debit@Act Fx Rate PQTD]   +  
			        
			              [Actual Subtotal Credit Less Debit@Act Fx Rate PQTD]   +  
			        
			                [Actual Other QTD], 
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Quarter-to-date (QTD)\Prior Quarter-to-date (PQTD)
		lineageTag: b66b0850-895b-452d-aae5-bcc1d8eb18b6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst BU Divide Credit Less Debit YTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Fcst BU Line-Item Credit Less Debit YTD]    +  
			    
			           [Fcst BU Subtotal Credit Less Debit YTD]  +  
			    
			            [Actual Other YTD], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			              [Fcst BU Line-Item Credit Less Debit YTD]    +  
			    
			           [Fcst BU Subtotal Credit Less Debit YTD]  +  
			    
			            [Actual Other YTD], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Year-to-date (YTD)\Forecast
		lineageTag: af7f2bf7-64c4-4ef8-81ba-3da0b95b382a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Fcst TD Divide Credit Less Debit YTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			    
			    // statement key in the numerator column 
			    
			    VAR calculationfincialstatementstablednumerator = 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			    
			                ) 
			    
			       
			     
			    VAR calculationfincialstatementstabledenominator= 
			    
			        CALCULATETABLE 
			    
			                (  
			    
			                Layout, 
			    
			                REMOVEFILTERS( Layout ),  
			    
			                Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			    
			                ) 
			    
			    // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			    
			    // numerator column 
			    
			    VAR numerator = 
			    
			        CALCULATE( 
			    
			          [Fcst TD Line-Item Credit Less Debit YTD]    +  
			    
			           [Fcst TD Subtotal Credit Less Debit YTD]   +  
			    
			            [Actual Other YTD], 
			    
			                calculationfincialstatementstablednumerator) 
			    
			           
			
			   
			    VAR denominator = 
			    
			        CALCULATE( 
			    
			           [Fcst TD Line-Item Credit Less Debit YTD]    +  
			    
			           [Fcst TD Subtotal Credit Less Debit YTD]   +  
			    
			            [Actual Other YTD], 
			    
			                Calculationfincialstatementstabledenominator, 
			    
			                REMOVEFILTERS(Account) 
			    
			           ) 
			           
			           
			    VAR result = DIVIDE (numerator,denominator)      
			    
			    RETURN 
			    
			        result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Year-to-date (YTD)\Forecast
		lineageTag: 2c16c02f-e143-48a6-975c-6e03e289673e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Plan Divide Credit Less Debit YTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			        
			        // statement key in the numerator column 
			        
			        VAR calculationfincialstatementstablednumerator = 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			        
			                    ) 
			        
			           
			         
			        VAR calculationfincialstatementstabledenominator= 
			        
			            CALCULATETABLE 
			        
			                    (  
			        
			                    Layout, 
			        
			                    REMOVEFILTERS( Layout ),  
			        
			                    Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			        
			                    ) 
			        
			        // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			        
			        // numerator column 
			        
			        VAR numerator = 
			        
			            CALCULATE( 
			        
			              [Plan Line-Item Credit Less Debit YTD]    +  
			        
			               [Plan Subtotal Credit Less Debit YTD]    +  
			        
			                [Actual Other YTD], 
			        
			                    calculationfincialstatementstablednumerator) 
			        
			               
			    
			       
			        VAR denominator = 
			        
			            CALCULATE( 
			        
			          [Plan Line-Item Credit Less Debit YTD]    +  
			        
			               [Plan Subtotal Credit Less Debit YTD]    +  
			        
			                [Actual Other YTD], 
			                    Calculationfincialstatementstabledenominator, 
			        
			                    REMOVEFILTERS(Account) 
			        
			               ) 
			               
			               
			        VAR result = DIVIDE (numerator,denominator)      
			        
			        RETURN 
			        
			            result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Year-to-date (YTD)\Plan
		lineageTag: 6d76740f-0b98-4e3a-baa5-2c3fca15e2ce

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other PYTD' = CALCULATE([Actual Other@Base Caculations TD], 'Effective Date'[PYTD] = 1)
		isHidden
		displayFolder: Step 05: Other\2_Comparison\Act + Fcst\Prior Year To Date (PYTD)
		lineageTag: 69a69a8a-cc5d-48b2-8358-57aabfc647bc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Act Fx Rate PYTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                  [Actual Line-Item Credit Less Debit@Act Fx Rate PYTD]   +  
			            
			                   [Actual Subtotal Credit Less Debit@Act Fx Rate PYTD]   +  
			            
			                     [Actual Other PYTD],
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			                          [Actual Line-Item Credit Less Debit@Act Fx Rate PYTD]   +  
			            
			                   [Actual Subtotal Credit Less Debit@Act Fx Rate PYTD]   +  
			            
			                     [Actual Other PYTD],
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\2_Comparison\Act ONLY\Year-to-date (YTD)\Prior Year-to-date (PYTD)
		lineageTag: b874a2a2-f328-4b1a-a0b5-652a5aebe24f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Fcst Fx Rate MTD' = ```
			 // Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                  [Actual Line-Item Credit Less Debit@Fcst Fx Rate MTD]    +  
			            
			                   [Actual Subtotal Credit Less Debit@Fcst Fx Rate MTD]    +  
			            
			                    [Actual Other MTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			              [Actual Line-Item Credit Less Debit@Fcst Fx Rate MTD]    +  
			            
			                   [Actual Subtotal Credit Less Debit@Fcst Fx Rate MTD]    +  
			            
			                    [Actual Other MTD],  
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 17340b31-8db8-47c9-b03f-43fc709ff7d2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Plan Fx Rate MTD' = ```
			 // Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                  [Actual Line-Item Credit Less Debit@Plan Fx Rate MTD]    +  
			            
			                  [Actual Subtotal Credit Less Debit@Plan Fx Rate MTD]   +  
			            
			                    [Actual Other MTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			               [Actual Line-Item Credit Less Debit@Plan Fx Rate MTD]    +  
			            
			                  [Actual Subtotal Credit Less Debit@Plan Fx Rate MTD]   +  
			            
			                    [Actual Other MTD], 
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: c35ef688-1c09-48ee-9b14-8de67e3d10ba

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@PY Fx Rate MTD' = ```
			 // Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                 [Actual Line-Item Credit Less Debit@PY Fx Rate MTD]    +  
			            
			                [Actual Subtotal Credit Less Debit@PY Fx Rate MTD]   +  
			            
			                    [Actual Other MTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			                    [Actual Line-Item Credit Less Debit@PY Fx Rate MTD]    +  
			            
			                [Actual Subtotal Credit Less Debit@PY Fx Rate MTD]   +  
			            
			                    [Actual Other MTD],  
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Month-to-date (MTD)
		lineageTag: 8c28c4b3-69d0-48f4-8650-4d09f0016e76

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Fcst Fx Rate QTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                  [Actual Line-Item Credit Less Debit@Fcst Fx Rate QTD]    +  
			            
			                   [Actual Subtotal Credit Less Debit@Fcst Fx Rate QTD]    +  
			            
			                    [Actual Other QTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			              [Actual Line-Item Credit Less Debit@Fcst Fx Rate QTD]    +  
			            
			                   [Actual Subtotal Credit Less Debit@Fcst Fx Rate QTD]    +  
			            
			                    [Actual Other QTD],  
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: 2170fdfa-bb2b-4511-9fbe-23fc3f461dbd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Plan Fx Rate QTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                  [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD]    +  
			            
			                  [Actual Subtotal Credit Less Debit@Plan Fx Rate QTD]   +  
			            
			                    [Actual Other QTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			               [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD]    +  
			            
			                  [Actual Subtotal Credit Less Debit@Plan Fx Rate QTD]   +  
			            
			                    [Actual Other QTD], 
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: 6f4c4e5b-76d9-4363-bcb8-d21d43c4fb75

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@PY Fx Rate QTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                 [Actual Line-Item Credit Less Debit@PY Fx Rate QTD]    +  
			            
			                [Actual Subtotal Credit Less Debit@PY Fx Rate QTD]   +  
			            
			                    [Actual Other QTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			                    [Actual Line-Item Credit Less Debit@PY Fx Rate QTD]    +  
			            
			                [Actual Subtotal Credit Less Debit@PY Fx Rate QTD]   +  
			            
			                    [Actual Other QTD],  
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Quarter-to-date (QTD)
		lineageTag: af8df203-f652-4519-8f2d-8b2901db01b1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Fcst Fx Rate YTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                  [Actual Line-Item Credit Less Debit@Fcst Fx Rate YTD]    +  
			            
			                   [Actual Subtotal Credit Less Debit@Fcst Fx Rate YTD]    +  
			            
			                    [Actual Other YTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			              [Actual Line-Item Credit Less Debit@Fcst Fx Rate YTD]    +  
			            
			                   [Actual Subtotal Credit Less Debit@Fcst Fx Rate YTD]    +  
			            
			                    [Actual Other YTD],  
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: fcf7414d-8328-4620-9e50-e0bfbb431452

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@Plan Fx Rate YTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                  [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD]    +  
			            
			                  [Actual Subtotal Credit Less Debit@Plan Fx Rate YTD]   +  
			            
			                    [Actual Other YTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			               [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD]    +  
			            
			                  [Actual Subtotal Credit Less Debit@Plan Fx Rate YTD]   +  
			            
			                    [Actual Other YTD], 
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: 1d28afc7-5479-4d8d-b06f-7664edeb99fa

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Divide Credit Less Debit@PY Fx Rate YTD' = ```
			// Part 1: Remove fillers from the layout table and select the income 
			            
			            // statement key in the numerator column 
			            
			            VAR calculationfincialstatementstablednumerator = 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Numerator] )  
			            
			                        ) 
			            
			               
			             
			            VAR calculationfincialstatementstabledenominator= 
			            
			                CALCULATETABLE 
			            
			                        (  
			            
			                        Layout, 
			            
			                        REMOVEFILTERS( Layout ),  
			            
			                        Layout[Income_Statement_Key] = MAX( Layout[Divide_Denominator] )  
			            
			                        ) 
			            
			            // Part 2: Calculate steps 03 to 08 for the Income_Statement_Key in the 
			            
			            // numerator column 
			            
			            VAR numerator = 
			            
			                CALCULATE( 
			            
			                 [Actual Line-Item Credit Less Debit@PY Fx Rate YTD]    +  
			            
			                [Actual Subtotal Credit Less Debit@PY Fx Rate YTD]   +  
			            
			                    [Actual Other YTD], 
			            
			                        calculationfincialstatementstablednumerator) 
			            
			                   
			        
			           
			            VAR denominator = 
			            
			                CALCULATE( 
			            
			                    [Actual Line-Item Credit Less Debit@PY Fx Rate YTD]    +  
			            
			                [Actual Subtotal Credit Less Debit@PY Fx Rate YTD]   +  
			            
			                    [Actual Other YTD],  
			                        Calculationfincialstatementstabledenominator, 
			            
			                        REMOVEFILTERS(Account) 
			            
			                   ) 
			                   
			                   
			            VAR result = DIVIDE (numerator,denominator)      
			            
			            RETURN 
			            
			                result
			```
		isHidden
		displayFolder: Step 06: Divide\3_Actuals and Comparison\Year-to-date (YTD)
		lineageTag: 4f603fdd-1899-428b-acca-2d880047d9b1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: cde3e9a7-a9e9-4418-9ba6-6c861e0ec912

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 B PY' = ```
			COALESCE(
			    [Actual Line-Item Credit Less Debit@Act Fx Rate PYTD],
			  [Actual Subtotal Credit Less Debit@Act Fx Rate PYTD],
			        [Actual Other YTD],           
			        
			       [Actual Divide Credit Less Debit@Act Fx Rate PYTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 573be7e0-b224-4ec1-ab3f-ad048aa9c5bc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 C Fcst TD' = ```
			COALESCE(
			    [Fcst TD Line-Item Credit Less Debit YTD],
			    [Fcst TD Subtotal Credit Less Debit YTD],
			    
			        [Actual Other YTD],           
			        
			       [Fcst TD Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Forecast TD]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 4c2051fc-0218-4d2e-879c-955bec6715a5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 D Fcts BU' = ```
			COALESCE(
			    [Fcst BU Line-Item Credit Less Debit YTD],
			    [Fcst BU Subtotal Credit Less Debit YTD],
			    
			        [Actual Other YTD],           
			        
			       [Fcst BU Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Forecast BU]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: e06ddb27-fbd0-431d-89d1-26d94ea8fba6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 E Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit YTD],
			    [Plan Subtotal Credit Less Debit YTD],
			        [Actual Other YTD],           
			        
			      [Plan Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: b8a86e68-eb48-4b48-a422-38154bbbfad4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 F' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 5a6b5edb-2904-4ac4-b48e-8703b81f3a72

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 G vs PY' = [View C1 A Act] - [View C1 B PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 41ee365d-5e21-4ea1-91d1-0cf96937140d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 H vs Fcst TD' = ([View C1 A Act] - [View C1 C Fcst TD]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: cbeca38d-1311-4730-a728-1c2ccd1ad1e0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 I vs Fcst BU' = ([View C1 A Act] - [View C1 D Fcts BU]) * [Show Value Forecast BU]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: ebb3de63-cfc0-4d79-8146-509d242a045e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 J vs Pln' = ( [View C1 A Act] - [View C1 E Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 22d5653a-c7a2-4075-a675-4d5b24a50348

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 K' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: b9861fae-865c-4680-929a-3e91d4e0ec38

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Show Value Plan' =
			var showvalues = values(Layout[Show_Values])
			
			var hasoneshowvalue = hasonevalue(Layout[Show_Values])
			
			var result = if(hasoneshowvalue, showvalues, blank())
			return  result
		isHidden
		displayFolder: Step 07: Show Values and Blanks
		lineageTag: 73ab1e21-b856-402b-808c-173d544e2e0c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 L vs PY, %' = DIVIDE( [View C1 G vs PY], [View C1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 7d8d7f36-0b5c-4a88-8d70-0a3f5fd409b6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 M vs Fcst TD, %' = DIVIDE( [View C1 H vs Fcst TD], [View C1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 3e688d8c-4c64-476d-b151-7abfb29f8c71

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 N vs Fcst BU, %' = DIVIDE( [View C1 I vs Fcst BU], [View C1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 90ada64a-79a8-421f-a98a-09b54ce9e383

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 O vs Pln, %' = DIVIDE( [View C1 J vs Pln], [View C1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall
		lineageTag: 254bfdd3-df14-4a42-85a8-d717437b49c7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 Format PY' = ```
			  // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			        
			        
			        
			        
			        VAR varianceadj = [View C1 G vs PY] * indicator
			        
			        
			        
			        VAR result = SWITCH(
			                TRUE( ),
			                varianceadj > 0, [Green],
			                varianceadj < 0, [Red]
			            )
			            
			            
			            
			            
			        RETURN
			            result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall\Formatting
		lineageTag: 73c89f69-3a6f-4fa1-808d-6b8acf31fcda

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 Format Fcst TD' = ```
			  // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C1 H vs Fcst TD] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall\Formatting
		lineageTag: 16d888be-a95b-416c-837e-75b6e8c07cdb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 Format Fcst BU' = ```
			 // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C1 I vs Fcst BU] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall\Formatting
		lineageTag: 924c16ed-1203-4d67-bb70-a82557470411

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C1 Format Pln' = ```
			   // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C1 J vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C1: Overall\Formatting
		lineageTag: 5aeea23c-9da7-4401-8c30-11d6cceccc60

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 8cbf633f-03f8-4f0c-ac1b-bb87a61fd132

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 B PY' = ```
			COALESCE(
			    [Actual Line-Item Credit Less Debit@Act Fx Rate PQTD],
			  [Actual Subtotal Credit Less Debit@Act Fx Rate PQTD],
			        [Actual Other QTD],           
			        
			       [Actual Divide Credit Less Debit@Act Fx Rate PQTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 28e5153e-1ec3-4920-8a17-dd606e2ec1c7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 C Fcst TD' = ```
			COALESCE(
			    [Fcst TD Line-Item Credit Less Debit QTD],
			    [Fcst TD Subtotal Credit Less Debit QTD],
			    
			        [Actual Other QTD],           
			        
			       [Fcst TD Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Forecast TD]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 2c55a4fb-e544-4dd9-b231-b56e361f7d26

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 D Fcts BU' = ```
			COALESCE(
			    [Fcst BU Line-Item Credit Less Debit QTD],
			    [Fcst BU Subtotal Credit Less Debit QTD],
			    
			        [Actual Other QTD],           
			        
			       [Fcst BU Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Forecast BU]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 37f27902-e495-4e6c-a8eb-1418ade41fb4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 E Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit QTD],
			    [Plan Subtotal Credit Less Debit QTD],
			        [Actual Other QTD],           
			        
			      [Plan Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 1ba90b30-b381-4c36-aeb4-d336c7f0c4e3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 F' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 1b8dc5a6-9461-4e05-9219-b61609d8c0a0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 G vs PY' = [View B1 A Act] - [View B1 B PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 946c663c-e1db-48c0-a188-5943542448aa

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 H vs Fcst TD' = ([View B1 A Act] - [View B1 C Fcst TD]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 7bd7ee15-33c3-4791-a6ed-88354168935a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 I vs Fcst BU' = ([View B1 A Act] - [View B1 D Fcts BU]) * [Show Value Forecast BU]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: c9d1b095-e9e9-45ef-8cfb-66b5b38316cf

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 J vs Pln' = ( [View B1 A Act] - [View B1 E Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 427c4bcc-2220-4cdd-9d65-4458864fb785

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 K' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 7eb66806-7064-4a8f-a780-1f53fabdcd1f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 L vs PY, %' = DIVIDE( [View B1 G vs PY], [View B1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 375c6fde-5578-457f-ba41-d578ae7388f6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 M vs Fcst TD, %' = DIVIDE( [View B1 H vs Fcst TD], [View B1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: ac273a5e-aa35-449a-b6e8-4c4cfcb67594

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 N vs Fcst BU, %' = DIVIDE( [View B1 I vs Fcst BU], [View B1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 97242607-9c82-4990-9c7d-4c8a72fa67a3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 O vs Pln, %' = DIVIDE( [View B1 J vs Pln], [View B1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall
		lineageTag: 3bcbffde-6dd0-4c3a-99e8-911f8e289e30

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 Format PY' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View B1 G vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall\Formatting
		lineageTag: c40e126b-cffa-4e35-a23d-9a90fe1664cf

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 Format Fcst TD' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View B1 H vs Fcst TD] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall\Formatting
		lineageTag: 624d56cc-9ad7-4796-8065-22040dc9717d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 Format Fcst BU' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View B1 I vs Fcst BU] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall\Formatting
		lineageTag: fcf0fa51-c1e7-4efd-a2e7-8ecd46ab06f5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B1 Format Pln' = ```
			   // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			        VAR varianceadj =  [View B1 J vs Pln] * indicator 
			        
			        VAR result = 
			        SWITCH(
			            TRUE(),
			            varianceadj > 0, [green],
			            varianceadj < 0, [Red],
			            [Gray]
			            
			        )
			               
			            RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B1: Overall\Formatting
		lineageTag: 2e8422e2-451b-4107-ab23-f53029a76db4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: a5151249-9e73-4979-b040-3d3f25c6832b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 B PY' = ```
			COALESCE(
			    [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD],
			  [Actual Subtotal Credit Less Debit@Act Fx Rate PMTD],
			        [Actual Other MTD],           
			        
			       [Actual Divide Credit Less Debit@Act Fx Rate PMTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: 4e6eb000-9d2a-4a65-b056-ac6aa2c94604

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 C Fcst TD' = ```
			COALESCE(
			    [Fcst TD Line-Item Credit Less Debit MTD],
			    [Fcst TD Subtotal Credit Less Debit MTD],
			    
			        [Actual Other MTD],           
			        
			       [Fcst TD Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Forecast TD]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: 053688ed-e5d1-44e8-a6b6-e239a2fccb04

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 D Fcts BU' = ```
			COALESCE(
			    [Fcst BU Line-Item Credit Less Debit MTD],
			    [Fcst BU Subtotal Credit Less Debit MTD],
			    
			        [Actual Other MTD],           
			        
			       [Fcst BU Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Forecast BU]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: e60e1f8c-c553-4cf5-a049-52ed9b245c1f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 E Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit MTD],
			    [Plan Subtotal Credit Less Debit MTD],
			        [Actual Other MTD],           
			        
			      [Plan Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: 5085485d-402f-482e-8ebe-8bb8ac5f9e27

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 F' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: 4e6deb17-ed97-4652-bb23-084cca3acdad

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 G vs PY' = [View A1 A Act] - [View A1 B PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: e54da6c5-c4a0-4414-8f90-1b816ef5cb91

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 H vs Fcst TD' = ([View A1 A Act] - [View A1 C Fcst TD]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: 416bc0a6-9d81-4d9c-967e-9424ec4b8354

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 I vs Fcst BU' = ([View A1 A Act] - [View A1 D Fcts BU]) * [Show Value Forecast BU]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: b45819ff-9b8d-407f-91c4-31109ac92064

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 J vs Pln' = ( [View A1 A Act] - [View A1 E Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: 0e012a3c-4b8c-4754-a084-c4c297459819

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 K' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: 149f00d3-deca-4b06-ac24-2d88281b8a05

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 L vs PY, %' = DIVIDE( [View A1 G vs PY], [View A1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: f765acd4-3d33-4cc6-8fee-d6d60b3c297c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 M vs Fcst TD, %' = DIVIDE( [View A1 H vs Fcst TD], [View A1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: aa7186f3-f2d2-4c05-8dc1-c2c658e78eb1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 N vs Fcst BU, %' = DIVIDE( [View A1 I vs Fcst BU], [View A1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: f4946e55-d774-40f2-a664-77c86fd3fbbc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 O vs Pln, %' = DIVIDE( [View A1 J vs Pln], [View A1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall
		lineageTag: 2fe4d605-fdb6-4b3e-a982-066281018e24

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 Format PY' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View A1 G vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall\Formatting
		lineageTag: cbe54ca4-4957-4ca4-aac0-213750324ea3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 Format Fcst TD' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View A1 H vs Fcst TD] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall\Formatting
		lineageTag: a1f60317-2531-44b6-b0b2-4d1d00cbeca2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 Format Fcst BU' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View A1 I vs Fcst BU] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall\Formatting
		lineageTag: 7fa2c749-01cf-415c-9148-a80e3cb00306

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A1 Format Pln' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View A1 J vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A1: Overall\Formatting
		lineageTag: aadbb166-4733-42dd-80c2-febc94eb9d97

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 A Act @PY' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@PY Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@PY Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@PY Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: ef2d784e-71ee-4e45-a76c-2786e6f0ae9c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 B Act @Fcst' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Fcst Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Fcst Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Fcst Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 639fb013-96e7-426d-8591-fd9fa5f2e1d2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 C Act @Plan' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Plan Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Plan Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Plan Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 395a16fd-223d-49c6-b065-a93bf1473328

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 D PY' = ```
			COALESCE(
			    [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD],
			  [Actual Subtotal Credit Less Debit@Act Fx Rate PMTD],
			        [Actual Other MTD],           
			        
			       [Actual Divide Credit Less Debit@Act Fx Rate PMTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 80e6cd1f-dfe3-49f7-9bcc-46ffdd452552

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 E Fcst TD' = ```
			COALESCE(
			    [Fcst TD Line-Item Credit Less Debit MTD],
			    [Fcst TD Subtotal Credit Less Debit MTD],
			    
			        [Actual Other MTD],           
			        
			       [Fcst TD Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Forecast TD]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 2d59f922-5901-49a3-9ccc-76125c3929bc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 F Fcts BU' = ```
			COALESCE(
			    [Fcst BU Line-Item Credit Less Debit MTD],
			    [Fcst BU Subtotal Credit Less Debit MTD],
			    
			        [Actual Other MTD],           
			        
			       [Fcst BU Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Forecast BU]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 5268ea07-aea6-4bbb-ae7f-2affbc4cfc4f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 G Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit MTD],
			    [Plan Subtotal Credit Less Debit MTD],
			        [Actual Other MTD],           
			        
			      [Plan Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: b643696d-14c5-4bc2-9096-24d90dd2ec5b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 H' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 6bccb740-5919-4e7a-8ee1-33f71c5b656e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 I vs PY' = [View A2 A Act @PY] - [View A2 D PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 379abc55-b02a-426c-85cb-87a128fe38e8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 J vs Fcst TD' = ([View A2 B Act @Fcst] - [View A2 E Fcst TD]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 4084f2e7-74e2-4282-b17d-9faa90bd06aa

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 K vs Fcst BU' = ([View A2 B Act @Fcst] - [View A2 F Fcts BU]) * [Show Value Forecast BU]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: c6bacd03-f569-40d2-85b3-1ce37e38e1f8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 L vs Pln' = ( [View A2 C Act @Plan] - [View A2 G Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 7e6bbf98-751a-4ca0-b2d9-c4ddab8daee6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 M' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: bc00ae0f-c076-42e9-a263-c84164c0f446

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 N vs PY, %' = DIVIDE( [View A2 i vs PY], [View A2 A Act @PY] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 60615450-b36a-4d33-bc50-272ad31c5b9a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 O vs Fcst TD, %' = DIVIDE( [View A2 j vs Fcst TD], [View A2 B Act @Fcst] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 4f6d08b6-6138-41e3-98dc-830942df6d1b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 P vs Fcst BU, %' = DIVIDE( [View A2 k vs Fcst BU], [View A2 B Act @Fcst] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: de1f2106-0ed8-4e99-befd-b9a008c6c4b0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 Q vs Pln, %' = DIVIDE( [View A2 l vs Pln], [View A2 C Act @Plan] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying
		lineageTag: 7ebc30e2-cc93-42d0-b853-8d812ebbc9bf

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 Format PY' = ```
			    // subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View A2 I vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying\Formatting
		lineageTag: 29e43609-4d79-44aa-8a1b-0ea834ba04fb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 Format Pln' = ```
			   // subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View A2 L vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying\Formatting
		lineageTag: 8441cda5-fad2-4465-806d-c6d3dac52dec

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 Format Fcst TD' = ```
			  // subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View A2 J vs Fcst TD] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying\Formatting
		lineageTag: aee00e82-0a74-479e-993c-e1ca3dd445d0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A2 Format Fcst BU' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View A2 K vs Fcst BU] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A2: Underlying\Formatting
		lineageTag: f13fff9c-c996-4581-8ba7-0f78e7af5ca6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 A Act @PY' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@PY Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@PY Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@PY Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 2aa174fd-b3f8-4603-9c3e-15886250f889

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 B Act @Fcst' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Fcst Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Fcst Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Fcst Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 37feb0ea-03e0-44ec-ae59-65becf245723

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 C Act @Plan' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Plan Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Plan Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 31605f86-3c48-4a19-aaf4-58e500a020dd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 D PY' = ```
			COALESCE(
			   [Actual Line-Item Credit Less Debit@Act Fx Rate PQTD],
			   
			   
			  [Actual Subtotal Credit Less Debit@Act Fx Rate PQTD],
			        [Actual Other QTD],           
			        [Actual Divide Credit Less Debit@Act Fx Rate PQTD],
			      
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: bcb7c78c-d906-4b76-9182-e1d857f1ef08

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 E Fcst TD' = ```
			COALESCE(
			    [Fcst TD Line-Item Credit Less Debit QTD],
			    [Fcst TD Subtotal Credit Less Debit QTD],
			    
			        [Actual Other QTD],           
			        
			       [Fcst TD Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Forecast TD]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: f71e8d9d-ff0b-414c-af48-65af5c0350c4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 F Fcts BU' = ```
			COALESCE(
			    [Fcst BU Line-Item Credit Less Debit QTD],
			    [Fcst BU Subtotal Credit Less Debit QTD],
			    
			        [Actual Other QTD],           
			        
			       [Fcst BU Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Forecast BU]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: a6a81072-ea2c-4a64-9ecf-14c2e02b7203

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 G Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit QTD],
			    [Plan Subtotal Credit Less Debit QTD],
			        [Actual Other QTD],           
			        
			      [Plan Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 105e9110-06bc-4e73-a14e-7afe0e4e2521

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 H' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 49d65a64-81ff-46f7-98fe-f34f62b4065e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 I vs PY' = [View B2 A Act @PY] - [View B2 D PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 69878624-ebc4-4f80-8a11-f11a2dedf641

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 J vs Fcst TD' = ([View B2 B Act @Fcst] - [View B2 E Fcst TD]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 8b952fcb-4686-4073-b108-e62ea8d530c7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 K vs Fcst BU' = ([View B2 B Act @Fcst] - [View B2 F Fcts BU]) * [Show Value Forecast BU]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: e63aa06b-d3d5-488a-8cdb-1cd1cb9b551a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 L vs Pln' = ( [View B2 C Act @Plan] - [View B2 G Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 6e75655f-259c-426b-a1b3-e4f6a9737f4d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 M' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 177cd941-cbbc-47b7-ab7d-bf6caf11a86a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 N vs PY, %' = DIVIDE( [View B2 i vs PY], [View B2 A Act @PY] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 9fce6de2-d6f9-484e-a80c-1c7a55d730a2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 O vs Fcst TD, %' = DIVIDE( [View B2 j vs Fcst TD], [View B2 B Act @Fcst] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 51b36a3a-15c0-4891-9029-4644c1f2829f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 P vs Fcst BU, %' = DIVIDE( [View B2 k vs Fcst BU], [View B2 B Act @Fcst] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 8be60582-cfca-46eb-964f-501e1523874b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 Q vs Pln, %' = DIVIDE( [View B2 l vs Pln], [View B2 C Act @Plan] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying
		lineageTag: 6e47911c-9669-47c9-b56a-1ac8f6a64135

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 Format PY' = ```
			 // subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View B2 I vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying\Formatting
		lineageTag: a6eb9665-0a88-4320-ac2d-bb10d48eb9a5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 Format Pln' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View B2 L vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying\Formatting
		lineageTag: a4ad142b-2f5e-4049-8aa8-4d51fa586e88

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 Format Fcst TD' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View B2 J vs Fcst TD] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying\Formatting
		lineageTag: c5b921e8-7002-4fe1-baf8-6affdcae703a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B2 Format Fcst BU' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View B2 K vs Fcst BU] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B2: Underlying\Formatting
		lineageTag: 7eb13eee-80b9-4782-b543-5e7a6b347635

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 A Act @PY' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@PY Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@PY Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@PY Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: cca5085e-6442-4427-b2cb-5909205a7cd2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 B Act @Fcst' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Fcst Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Fcst Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Fcst Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: b5ce6c34-b39b-4a6e-9ec0-9993eda846fd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 C Act @Plan' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Plan Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Plan Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: efc2f4f6-92ec-4112-9ce6-72d104a5cc4c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 D PY' = ```
			COALESCE(
			   [Actual Line-Item Credit Less Debit@Act Fx Rate PYTD],
			   
			   
			   
			  [Actual Subtotal Credit Less Debit@Act Fx Rate PYTD],
			        [Actual Other YTD],           
			        [Actual Divide Credit Less Debit@Act Fx Rate PYTD],
			      
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: e3d3e4c9-d7b9-4cd5-8892-68b7225a05ed

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 E Fcst TD' = ```
			COALESCE(
			    [Fcst TD Line-Item Credit Less Debit YTD],
			    [Fcst TD Subtotal Credit Less Debit YTD],
			    
			        [Actual Other YTD],           
			        
			       [Fcst TD Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Forecast TD]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: ae9bbd5f-1dbd-4743-8732-08e933e2fc57

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 F Fcts BU' = ```
			COALESCE(
			    [Fcst BU Line-Item Credit Less Debit YTD],
			    [Fcst BU Subtotal Credit Less Debit YTD],
			    
			        [Actual Other YTD],           
			        
			       [Fcst BU Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Forecast BU]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: c6dc22c1-fd0e-4c95-99cb-12bf1f8b4c10

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 G Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit YTD],
			    [Plan Subtotal Credit Less Debit YTD],
			        [Actual Other YTD],           
			        
			      [Plan Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: a71c40db-6ad6-4e31-a79c-9189a9e0c904

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 H' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: 610735c6-991b-476b-8b4e-408e6916bb7e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 I vs PY' = [View C2 A Act @PY] - [View C2 D PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: afce7ebe-faa5-48d8-be6f-1dae077714b2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 J vs Fcst TD' = ([View C2 B Act @Fcst] - [View C2 E Fcst TD]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: 7a662bc3-7fd2-4250-a037-6544fb6eb581

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 K vs Fcst BU' = ([View C2 B Act @Fcst] - [View C2 F Fcts BU]) * [Show Value Forecast BU]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: 848a5690-30fc-44bd-9463-8c19e24a1185

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 L vs Pln' = ( [View C2 C Act @Plan] - [View C2 G Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: 580d6aa8-5040-41e1-affc-f7dcf8895cf7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 M' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: 2dd1c092-d414-4441-b49c-b42d6dff2787

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 N vs PY, %' = DIVIDE( [View C2 i vs PY], [View C2 A Act @PY] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: 8ae52469-9891-457f-be7a-17fbe9173fbb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 O vs Fcst TD, %' = DIVIDE( [View C2 j vs Fcst TD], [View C2 B Act @Fcst] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: 761a5016-e778-4644-986d-2d9c0bea0711

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 P vs Fcst BU, %' = DIVIDE( [View C2 k vs Fcst BU], [View C2 B Act @Fcst] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: 505c32fd-55e5-4084-8cee-7e356dd25d7e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 Q vs Pln, %' = DIVIDE( [View C2 l vs Pln], [View C2 C Act @Plan] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying
		lineageTag: e090b825-b5d4-4d4f-b2c3-af50bba10e05

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 Format PY' = ```
			   // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C2 I vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying\Formatting
		lineageTag: 7dd4a05e-1751-45a5-9224-2e7d8744fb17

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 Format Pln' = ```
			   // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C2 L vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying\Formatting
		lineageTag: 11032557-3ed2-47a3-bdc6-2714349213e1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 Format Fcst TD' = ```
			   // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C2 J vs Fcst TD] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying\Formatting
		lineageTag: abd4edb9-2408-49f8-a8b1-21303fdca527

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C2 Format Fcst BU' = ```
			  // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C2 K vs Fcst BU] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C2: Underlying\Formatting
		lineageTag: 5c9c6e36-c6ef-4308-b695-8cca485815b3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 A Act @Act Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: 89db119f-24fd-423e-8d55-80958f944683

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 B Act @PY Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@PY Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@PY Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@PY Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: 37498dd1-628c-42e6-91ef-430114f3375b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 C Act @Fcst Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Fcst Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Fcst Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Fcst Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: b0c8536f-7c4b-40cb-abed-2b060259b382

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 D Act @Plan Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Plan Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Plan Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Plan Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: f9f687f1-b472-4e60-8a3e-cfb232b4b218

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: ec58ddba-4585-4c28-9a9f-e747241ad981

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 F vs PY' = [View A3 A Act @act fx] - [View A3 B Act @PY fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: 69b29384-60d9-4a4b-996e-4dc18a43fc59

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 G vs Fcst' = ([View A3 A Act @act fx] - [View A3 C Act @Fcst fx]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: 29ace286-3163-464d-ad60-7aacf4b94c7d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 H vs Pln' = ( [View A3 A Act @act fx] -  [View A3 D Act @plan fx]  )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: 83a582fd-2cec-4e27-90ce-5e9cb329019d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 I' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: 2416a666-eb9e-4230-832c-b35a60a0fdf8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 J vs PY, %' = DIVIDE( [View A3 F vs PY], [View A3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: 96b1f246-b37e-4f81-9ee7-2fa37a3d70cc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 K vs Fcst, %' = DIVIDE( [View A3 G vs Fcst], [View A3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: 79320402-53fa-408e-95b2-2cd77fd38e95

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 L vs Pln, %' = DIVIDE( [View A3 H vs Pln], [View A3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx
		lineageTag: b78982b8-bfbb-4be2-b98f-e98d4643e66a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 Format PY' = ```
			 // subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View A3 F vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx\Formatting
		lineageTag: aa7d571f-01df-49d7-9a1f-3fec3e735974

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 Format Fcst' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View A3 G vs Fcst] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx\Formatting
		lineageTag: a1dcf62e-9e1a-4436-b487-228c4d2997c2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View A3 Format Pln' = ```
			 // subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View A3 h vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View A: MTD vs PY, Fcst, and Plan\View A3: Fx\Formatting
		lineageTag: 7e6bdbe2-5393-44f3-ab18-7572ed949690

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 A Act @Act Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: e0a0e172-db5c-42e4-a040-fa4de3f6d66e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 B Act @PY Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@PY Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@PY Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@PY Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: fcfb21d9-610e-4e00-8658-fb328f35c753

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 C Act @Fcst Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Fcst Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Fcst Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Fcst Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: f38dfa5a-8666-4f07-8643-89332d7ee455

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 D Act @Plan Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Plan Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Plan Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Plan Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: 8d179101-0e4b-4a8c-bc01-d70a72ee7e14

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: 3377ba75-3a64-4f4f-9f70-93e066bca528

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 F vs PY' = [View B3 A Act @act fx] - [View B3 B Act @PY fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: d0278e5e-7096-457e-b61b-3f3b260b3e90

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 G vs Fcst' = ([View B3 A Act @act fx] - [View B3 C Act @Fcst fx]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: 2eaf63e8-4f22-4ef4-8bbf-b0c461de1943

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 H vs Pln' = ( [View B3 A Act @act fx] -  [View B3 D Act @plan fx]  )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: 74042eac-a7fb-482d-83e8-404ab957bbc3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 I' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: 73d264c2-0e2c-4196-b7dc-d98b0898192a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 J vs PY, %' = DIVIDE( [View B3 F vs PY], [View B3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: f2812b3e-6904-42eb-a004-10a58a9eecf2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 K vs Fcst, %' = DIVIDE( [View B3 G vs Fcst], [View B3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: 34ec91ba-e592-4678-962b-1db6ad1cbf62

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 L vs Pln, %' = DIVIDE( [View B3 H vs Pln], [View B3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx
		lineageTag: 36b1c16a-a393-4689-8919-85017ddcc481

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 Format PY' = ```
			// subtotal
			    VAR NCLD_filter_context_calculated_table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			            Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			        )
			    VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			
			    //percentage
			    VAR numeratormax = MAX( Layout[Divide_Numerator] )
			    VAR Pct_Table =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= numeratormax,
			            Layout[Income_Statement_Key] <= numeratormax
			        )
			    VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			    VAR NCLD_filter_context_calculated_table_Pct =
			        CALCULATETABLE(
			            Layout,
			            REMOVEFILTERS( Layout ),
			            Layout[Income_Statement_Key] >= subtotalfrom,
			            Layout[Income_Statement_Key] <= subtotalto
			        )
			    VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			
			
			
			
			    // indicatpr
			    VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View B3 F vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx\Formatting
		lineageTag: 246a447c-0a0a-4811-90b8-ba9bd9134aef

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 Format Fcst' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View B3 G vs Fcst] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx\Formatting
		lineageTag: 05abae30-d138-4bc9-be25-5c7e230124be

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View B3 Format Pln' = ```
			  // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View B3 h vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View B: QTD vs PY, Fcst, and Plan\View B3: Fx\Formatting
		lineageTag: db73a132-db72-4328-a1cd-eda3fe3e84c2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 A Act @Act Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: b189d600-bd16-4824-9586-33ff8792cb28

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 B Act @PY Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@PY Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@PY Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@PY Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: dbe6f85f-998a-4b05-9af8-d80373e22d65

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 C Act @Fcst Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Fcst Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Fcst Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Fcst Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: 9a96b66a-2667-4e28-bfe7-879ae42eeedb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 D Act @Plan Fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Plan Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Plan Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: 70de475d-19dd-432e-9f4a-5d3952ad11b0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: 23751041-4451-4be0-a67a-3576d253d530

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 F vs PY' = [View C3 A Act @act fx] - [View C3 B Act @PY fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: 7995aba2-199f-466e-b659-c586077c67fe

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 G vs Fcst' = ([View C3 A Act @act fx] - [View C3 C Act @Fcst fx]) * [Show Value Forecast TD]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: 47b25cf9-1354-4f47-a3f3-17217b954a0d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 H vs Pln' = ( [View C3 A Act @act fx] -  [View C3 D Act @plan fx]  )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: de46ae08-277b-4962-ad36-42d50a119485

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 I' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: f293a02b-6c68-4cbd-b6a6-1998c33efc96

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 J vs PY, %' = DIVIDE( [View C3 F vs PY], [View C3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: a2ed942e-7f74-431c-954d-83d32d90008d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 K vs Fcst, %' = DIVIDE( [View C3 G vs Fcst], [View C3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: d6f4d2d9-1ad0-4a81-bfb5-c5c20caf761e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 L vs Pln, %' = DIVIDE( [View C3 H vs Pln], [View C3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx
		lineageTag: 192062a5-88e6-40be-b67b-9c91260a9727

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 Format PY' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C3 F vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx\Formatting
		lineageTag: 30044f7d-2ac5-4829-a41c-d0eff01c6bdf

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 Format Fcst' = ```
			   // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C3 G vs Fcst] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx\Formatting
		lineageTag: 729a12b7-e668-4bb6-87c3-b0f87701c8e7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View C3 Format Pln' = ```
			  // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View C3 h vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View C: YTD vs PY, Fcst, and Plan\View C3: Fx\Formatting
		lineageTag: b25d578e-3e33-4a73-bda0-48eafbe56cea

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: fa0dea0d-29a0-4870-9d6f-0079671ac3a0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 B Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit MTD],
			    [Plan Subtotal Credit Less Debit MTD],
			        [Actual Other MTD],           
			        
			      [Plan Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 74ff7b28-6db3-4442-9d00-37ca643d364f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 C vs Pln' = ( [View D1 A Act] - [View D1 B Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: adc2ccc8-a7ee-47cd-8150-f24370bcd3bc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 D vs Pln, %' = DIVIDE( [View D1 C vs Pln], [View D1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: b50f3b79-b651-4291-a2fa-02a64bb31df5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: b8b005a4-c15d-4fce-9cc2-c6fdab5c6e31

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 F Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 2893b5b6-5011-4a00-9367-a08451e57898

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 G Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit QTD],
			    [Plan Subtotal Credit Less Debit QTD],
			        [Actual Other QTD],           
			        
			      [Plan Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 74dc640f-7d6e-4c74-a2f6-c3a478f16bb7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 H vs Pln' = ( [View D1 F Act] - [View D1 G Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: bd73cdf8-10e4-4937-9240-5426b7419313

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 I vs Pln, %' = DIVIDE( [View D1 H vs Pln], [View D1 F Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: cacd2a85-5ed9-4134-a8f8-19d95a9a2640

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 51d0996c-3ecb-4d4b-b510-867c957b7c6d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 K Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 728f4a81-a490-4328-b94d-9bdfc02d6c3d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 L Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit YTD],
			    [Plan Subtotal Credit Less Debit YTD],
			        [Actual Other YTD],           
			        
			      [Plan Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: caeb048c-b61e-4c29-a1b3-6aa79c7d0c7f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 M vs Pln' = ( [View D1 K Act] - [View D1 l Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 84ba2521-1a01-4aa3-bc36-2ea8073892ba

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 N vs Pln, %' = DIVIDE( [View D1 M vs Pln], [View D1 K Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 1a4199c7-57be-4136-913e-fa2bde06d4a9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 O' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 844df496-f7f9-48cb-8a3d-e4c7f29457e5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 P Act' =
			COALESCE(
			    [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			       [Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			        [Actual Other YTD],
			       [Actual Divide Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 81d6a0b7-d507-4d74-b9cd-0d5fc3974839

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 Q Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit CY],
			     [Plan Subtotal Credit Less Debit CY],
			    
			        [Actual Other YTD],           
			        
			     [Plan Divide Credit Less Debit CY],
			     
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 86e77a4b-269f-4597-85bd-d46b2049ff97

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 R vs Pln' = ( [View D1 P Act] - [View D1 Q Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 104f0309-7683-464e-87f4-7ffa04594bf7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 S vs Pln, %' = DIVIDE( [View D1 R vs Pln], [View D1 P Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall
		lineageTag: 35407d1c-1b57-4628-a245-e7b3223a5d8d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 Format MTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D1 C vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall\Formatting
		lineageTag: abce5368-56d4-41f0-adec-448c44d46260

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 Format QTD' = ```
			  // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D1 H vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall\Formatting
		lineageTag: d05841c1-29d7-4a14-baee-6cf23fb3082f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 Format YTD' = ```
			 // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D1 m vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall\Formatting
		lineageTag: 73354cb7-ad62-4825-b3b9-b15db0f284a7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D1 Format FY' = ```
			  // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View D1 r vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D1: Overall\Formatting
		lineageTag: 9313dbec-b02d-4d15-8cbd-a7401dd377eb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 7c403b39-ab38-4643-8412-43ac9ded6605

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 B Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit MTD],
			    [Plan Subtotal Credit Less Debit MTD],
			        [Actual Other MTD],           
			        
			      [Plan Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 1bd7da89-de14-4fdd-b301-252561383797

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 C vs Pln' = ( [View D2 A Act] - [View D2 B Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 0e902ee9-b772-4389-98a6-d0f08cd6d213

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 D vs Pln, %' = DIVIDE( [View D2 C vs Pln], [View D2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: d9e6b24b-b876-4db8-b821-bf5512ef29ea

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: c100274f-c976-4046-806a-b685cb65d8ed

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 F Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 4fd2f314-fad3-438e-ac1e-2794a7540c14

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 G Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit QTD],
			    [Plan Subtotal Credit Less Debit QTD],
			        [Actual Other QTD],           
			        
			      [Plan Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 0319d4b1-ff78-4c6e-855f-689bb99d9457

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 H vs Pln' = ( [View D2 f Act] - [View d2 g Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: a6d5c0a1-8c96-4479-aa77-542e7d1ef7d1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 I vs Pln, %' = DIVIDE( [View D2 H vs Pln], [View D2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 9784b2a4-216b-403a-a33d-92abf6b8e710

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: edeac0b8-2321-491d-85c3-fd99e07a183e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 K Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 63888c9c-a0eb-4e3b-a98f-704785efbbe8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 L Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit YTD],
			    [Plan Subtotal Credit Less Debit YTD],
			        [Actual Other YTD],           
			        
			      [Plan Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 84815b58-f2bc-4665-93dc-3603c0c00a48

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 M vs Pln' = ( [View D2 k Act] - [View D2 l Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: b5d89ab7-969d-4a6d-8cde-c269feccb828

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 N vs Pln, %' = DIVIDE( [View D2 C vs Pln], [View D2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 4ae8d908-4ca9-44ef-bac8-96969af473db

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 O' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 56fc5091-ee10-4819-a99d-7ad901ce77b7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 P Act' =
			COALESCE(
			    [Actual Line-Item Credit Less Debit@plan Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			       [Actual Subtotal Credit Less Debit@plan Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			        [Actual Other YTD],
			       [Actual Divide Credit Less Debit@plan Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 0e3d5cd5-5cf5-4ca0-b404-ef928c4bebf6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 Q Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit CY],
			     [Plan Subtotal Credit Less Debit CY],
			    
			        [Actual Other YTD],           
			        
			     [Plan Divide Credit Less Debit CY],
			     
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 8faf5dda-93a0-4699-9b36-54a88378ef52

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 R vs Pln' = ( [View D2 P Act] - [View D2 Q Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: e9f25d3b-8bbf-42f3-9a5a-1a1b9b22e950

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 S vs Pln, %' = DIVIDE( [View D2 R vs Pln], [View D2 P Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying
		lineageTag: 53a60dfa-ed5a-4a71-9352-8d5a9e07bd61

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 Format MTD' = ```
			   // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D2 C vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying\Formatting
		lineageTag: ef40caa6-9a71-4d14-89c3-8580967f7b52

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 Format QTD' = ```
			 // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D2 H vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying\Formatting
		lineageTag: 74c841c5-d273-4efe-89e0-72c6f7cff101

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 Format YTD' = ```
			  // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D2 m vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying\Formatting
		lineageTag: aad5427c-0c51-45fa-b3ae-77bb3abec6c5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D2 Format FY' = ```
			   // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D2 r vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D2: Underlying\Formatting
		lineageTag: e62b5319-d341-4ebd-80c6-9a451a97d709

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 A Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 1d5cd896-b2d2-4987-8990-7ec9760f6980

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 B Act @pln fx' = ```
			COALESCE(
			 
			        [Actual Line-Item Credit Less Debit@plan Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 5efaab9c-ee5a-4dd8-ba9f-1e98e75f04b8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 C vs Pln' = ( [View D3 A Act @act fx] - [View D3 B Act @pln fx] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 8b2538f5-1d4e-4e81-9a58-d30a299df81e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 D vs Pln, %' = DIVIDE( [View D3 C vs Pln], [View D3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 382930fb-6244-46e5-a41e-8ead9304690f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: fe639f52-ca00-460f-9273-bdb71e8e9b49

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 F Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: b4ba0632-3d32-430e-b254-b952bdc9ced4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 G Act @pln fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate QTD],
			    [Blank rows] ) * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 88709b5f-c75c-42df-8697-55b3796429d7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 H vs Pln' = ( [View D3 F Act @act fx] - [View D3 G Act @pln fx] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 342ec987-f446-465e-996f-dd4230ec0804

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 I vs Pln, %' = DIVIDE( [View D3 C vs Pln], [View D3 F Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: f26a082e-4312-47a5-a500-e1fa759ebce0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 26a20895-64d8-4deb-a1d1-e61dbfae3363

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 K Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 1837ae71-e92b-45a5-87f7-d3aab9e64e4f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 L Act @pln fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: feda0940-0dfc-42c6-8a99-b3239031cdb3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 M vs Pln' = ( [View D3 K Act @act fx] - [View D3 L Act @pln fx] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: fd04711f-7640-4c98-9e49-1cd47849ec10

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 N vs Pln, %' = DIVIDE( [View D3 C vs Pln], [View D3 K Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx
		lineageTag: 7232d621-78a3-407f-99c9-6934d07763c2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 Format MTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View D3 C vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx\Formatting
		lineageTag: b31332b7-ca4c-40ba-a7f6-a1b160092c92

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 Format QTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D3 H vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx\Formatting
		lineageTag: 9f1dc320-f494-4629-a5e1-5c1832b9977c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View D3 Format YTD' = ```
			 // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View D3 m vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View D: FY Fcst 1 vs Plan\View D3: Fx\Formatting
		lineageTag: 7bfbed21-c753-4d49-9689-6a238e6c92fc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 3b6b6731-3de4-407e-9569-8cd810ae027c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 B Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit MTD],
			    [Plan Subtotal Credit Less Debit MTD],
			        [Actual Other MTD],           
			        
			      [Plan Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 35c2d49e-8305-4fe6-af82-9a72f1c9f8fa

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 C vs Pln' = ( [View E1 A Act] - [View E1 B Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 3867c622-36cc-451d-a434-051e3d18e6eb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 D vs Pln, %' = DIVIDE( [View E1 C vs Pln], [View E1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 1dee3ba7-8da2-4fab-a9e8-a17ae5889991

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: f1776c04-6c4b-4355-abfa-fc994fcfa31a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 F Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 5aa8412c-9d82-41b3-aaec-986ac30f6538

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 G Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit QTD],
			    [Plan Subtotal Credit Less Debit QTD],
			        [Actual Other QTD],           
			        
			      [Plan Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 4329e03a-cb77-4bd0-80c1-e21edacc67ad

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 H vs Pln' = ( [View E1 F Act] - [View E1 G Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 0f71ec38-d4f3-4867-a0f7-17cc07ba0db9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 I vs Pln, %' = DIVIDE( [View E1 H vs Pln], [View E1 F Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: b9bcd37c-3aa3-4ce8-bcd5-37cb1d9a0702

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: ea5ffba0-d204-4131-909c-dde5ff4d3feb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 K Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: b0e69dbc-830e-4345-96fc-cfdabe92b31d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 L Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit YTD],
			    [Plan Subtotal Credit Less Debit YTD],
			        [Actual Other YTD],           
			        
			      [Plan Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 104b2a21-d07b-4f41-9fc4-a946a961af1c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 M vs Pln' = ( [View E1 K Act] - [View E1 l Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: b901ad1d-e3f7-4968-bf4b-01c5b16f0286

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 N vs Pln, %' = DIVIDE( [View E1 M vs Pln], [View E1 K Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: cea352a5-526c-480d-95e5-59736f806109

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 O' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: 80410b05-e0e0-48d1-b03d-9e5740d229b2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 P Act' =
			COALESCE(
			    [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			       [Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			        [Actual Other YTD],
			       [Actual Divide Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: f1267286-51dd-4f38-8053-061961b8c94d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 Q Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit CY],
			     [Plan Subtotal Credit Less Debit CY],
			    
			        [Actual Other YTD],           
			        
			     [Plan Divide Credit Less Debit CY],
			     
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: b6ef5820-917a-4d5b-9e56-67c5995713f7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 R vs Pln' = ( [View E1 P Act] - [View E1 Q Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: c2ecbf2a-238d-4bcb-99dc-0296b9f20d4c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 S vs Pln, %' = DIVIDE( [View E1 R vs Pln], [View E1 P Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall
		lineageTag: e031676b-48ef-48ec-bbec-175d110561d9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 Format MTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E1 C vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall\Formatting
		lineageTag: 62f73e89-351c-409a-b587-1f770f44495c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 Format QTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E1 H vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall\Formatting
		lineageTag: 38d040ab-7388-435c-a690-57ae63076685

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 Format YTD' = ```
			 // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E1 m vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall\Formatting
		lineageTag: 692b9664-1cfd-494f-afca-b649f6deb77e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E1 Format FY' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View E1 r vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E1: Overall\Formatting
		lineageTag: 865cdb55-1f1b-468e-8297-b4cf9204813e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 0f239c54-a059-43c1-a48d-f84fd949c1f6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 B Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit MTD],
			    [Plan Subtotal Credit Less Debit MTD],
			        [Actual Other MTD],           
			        
			      [Plan Divide Credit Less Debit MTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: b689cfe5-255e-4def-bb1c-108748edf19e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 C vs Pln' = ( [View E2 A Act] - [View E2 B Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 3b8828c0-0ded-4a27-8149-0482f18670ee

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 D vs Pln, %' = DIVIDE( [View E2 C vs Pln], [View E2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 788f4930-4ba6-4055-b2b6-0075cb7e6b35

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 2373c7ff-7d64-4f0a-8273-d7828839316c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 F Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 37d43bd6-2c39-4fb0-80d3-025a0b53f827

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 G Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit QTD],
			    [Plan Subtotal Credit Less Debit QTD],
			        [Actual Other QTD],           
			        
			      [Plan Divide Credit Less Debit QTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 7750758e-f970-4cb4-b9c8-9b5a09f7b4c4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 H vs Pln' = ( [View E2 f Act] - [View E2 g Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: c02d5358-50e1-488f-9da4-43b49899082f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 I vs Pln, %' = DIVIDE( [View E2 H vs Pln], [View E2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 35e45540-6994-447e-91d6-30322915e67c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 9cf756ea-dd0d-4ed8-a7d7-00201da5a550

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 K Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 3e3a53f5-d310-4778-9a4a-f36522b1ba74

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 L Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit YTD],
			    [Plan Subtotal Credit Less Debit YTD],
			        [Actual Other YTD],           
			        
			      [Plan Divide Credit Less Debit YTD],
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: eb06fc72-20bf-4c5e-8b70-ed0d24994414

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 M vs Pln' = ( [View E2 k Act] - [View E2 l Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: b8f57025-af54-4f7b-abb7-eff891399371

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 N vs Pln, %' = DIVIDE( [View E2 C vs Pln], [View E2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: d750b476-9669-4097-8ba8-e471a982f81b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 O' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: fcf3de16-2a46-4678-ba7d-d105b8062347

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 P Act' =
			COALESCE(
			    [Actual Line-Item Credit Less Debit@plan Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			       [Actual Subtotal Credit Less Debit@plan Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			        [Actual Other YTD],
			       [Actual Divide Credit Less Debit@plan Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 5480155b-f9ee-46f0-9751-c1d347535464

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 Q Pln' = ```
			COALESCE(
			 
			    [Plan Line-Item Credit Less Debit CY],
			     [Plan Subtotal Credit Less Debit CY],
			    
			        [Actual Other YTD],           
			        
			     [Plan Divide Credit Less Debit CY],
			     
			    [Blank rows] ) * [Show Value Plan]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: ed589371-450f-4d47-9e52-e3222b2aa16a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 R vs Pln' = ( [View E2 P Act] - [View E2 Q Pln] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: 9465e0f7-49be-40d6-99e0-c78be714dcf0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 S vs Pln, %' = DIVIDE( [View E2 R vs Pln], [View E2 P Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying
		lineageTag: c97cdc82-d343-435f-a5ee-a732d4f925ac

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 Format MTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E2 C vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying\Formatting
		lineageTag: 9832e05b-192a-4812-b2a0-b61574921d56

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 Format QTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E2 H vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying\Formatting
		lineageTag: 18571888-c4c8-4852-87be-85f291bd8403

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 Format YTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View E2 m vs Pln] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying\Formatting
		lineageTag: e504e2ae-c3ee-4e74-9ced-70557512d569

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E2 Format FY' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E2 r vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E2: Underlying\Formatting
		lineageTag: 00f7176e-145c-401e-98e3-58ff8485aff7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 A Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: ab498cab-53e1-4aca-98f5-31ccd5404177

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 B Act @pln fx' = ```
			COALESCE(
			 
			        [Actual Line-Item Credit Less Debit@plan Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: d12d8efd-375b-4443-b298-8810d19ab72d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 C vs Pln' = ( [View E3 A Act @act fx] - [View E3 B Act @pln fx] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: 6a773673-3b5c-411f-b7e0-75fec6915f4f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 D vs Pln, %' = DIVIDE( [View E3 C vs Pln], [View E3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: 1662a2dc-7def-4f67-8b0b-354e42cb8eaf

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: 88f3436c-eabc-443c-bc5b-732d6832717c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 F Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: 23b93520-cdab-4202-a6c3-558b00395035

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 G Act @pln fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate QTD],
			    [Blank rows] ) * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: 4bfc2ee6-efd3-45a9-a3ec-1ed3334eb682

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 H vs Pln' = ( [View E3 F Act @act fx] - [View E3 G Act @pln fx] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: bf42664b-a72c-4182-b58c-1e70d8503845

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 I vs Pln, %' = DIVIDE( [View E3 C vs Pln], [View E3 F Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: 10ad478b-6d1d-47ac-9a33-c816face04d7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: b85abd58-9913-424d-8197-fe4691923ca3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 K Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: 3df8e350-c542-4820-83d0-86458ca3e59c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 L Act @pln fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@plan Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@plan Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@plan Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: 3a408af6-73b8-482c-9ecd-637a78add6fe

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 M vs Pln' = ( [View E3 K Act @act fx] - [View E3 L Act @pln fx] )  * [Show Value Plan]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: d3825ab7-3b7d-493a-814f-b6b77764d5bc

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 N vs Pln, %' = DIVIDE( [View E3 C vs Pln], [View E3 K Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx
		lineageTag: ac0c99f3-31e3-4585-b398-295993aaaa57

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 Format MTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E3 C vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx\Formatting
		lineageTag: b4a76bb1-c973-4bc0-a13c-79a67a3f723c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 Format QTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E3 H vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx\Formatting
		lineageTag: c7f9fb95-f8fa-419e-b5a3-ffe394eba6a9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View E3 Format YTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View E3 m vs Pln] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View E: FY Fcst 2 vs Plan\View E3: Fx\Formatting
		lineageTag: 21d47aee-70a9-41e8-97b9-b8eb657c495a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 2f9d213a-1337-4108-80a8-b133ed1ea7f9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 B PY' = ```
			COALESCE(
			               [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD],
			      [Actual Subtotal Credit Less Debit@Act Fx Rate PMTD],
			            [Actual Other PMTD],           
			            
			           [Actual Divide Credit Less Debit@Act Fx Rate PMTD],
			        [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: f1fc28a5-ae38-46a8-8d79-690a28bbaf35

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 C vs PY' = [View F1 A Act] - [View F1 B PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 427d42f9-9207-4d2f-b5a1-3183f9583d20

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 D vs PY, %' = DIVIDE( [View F1 C vs PY], [View F1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 11eadd42-36e8-4e0d-9135-2f9c1ecd8d2e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 6423e5ab-0ce6-4585-8136-ce4ff98550c9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 F Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: f171d17c-1fb9-45ee-b7a5-b850e6d0660d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 G PY' = ```
			COALESCE(
			               [Actual Line-Item Credit Less Debit@Act Fx Rate PQTD],
			      [Actual Subtotal Credit Less Debit@Act Fx Rate PQTD],
			            [Actual Other PQTD],           
			            
			           [Actual Divide Credit Less Debit@Act Fx Rate PQTD],
			        [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 4693690c-9239-486e-aaca-68ce37a82453

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 H vs PY' = [View F1 F Act] - [View F1 G PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: a0cb1b57-b75d-4ba9-9ea1-ddd5e2074ffb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 I vs PY, %' = DIVIDE( [View F1 H vs PY], [View F1 F Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 0e32c769-6e06-4aaa-a0c1-d54749c7ebf9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 8f4f71c8-c628-4b93-88d7-2e50ee7dee6a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 K Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 773b6c2f-8cff-4023-b897-71b8fde3780c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 L PY' = ```
			COALESCE(
			               [Actual Line-Item Credit Less Debit@Act Fx Rate PYTD],
			      [Actual Subtotal Credit Less Debit@Act Fx Rate PYTD],
			            [Actual Other PYTD],           
			            
			           [Actual Divide Credit Less Debit@Act Fx Rate PYTD],
			        [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: c8c5f1df-6ee5-4b93-a37d-233d8d9d8ec5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 M vs PY' = [View F1 K Act] - [View F1 l PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 6a8dcff6-6114-4374-9f70-5fa45a483ebd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 N vs PY, %' = DIVIDE( [View F1 M vs PY], [View F1 K Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: f64c17bf-6437-42ea-b266-bd1446229078

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 O' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 761d48cf-3cd3-4cbf-b50f-ead5c1b22d29

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 P Act' =
			COALESCE(
			    [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			       [Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			        [Actual Other YTD],
			       [Actual Divide Credit Less Debit@Act Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: d6e2cf3f-bd8d-4abe-ab4d-d2dad36e3d8b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 Q PY' = ```
			COALESCE(
			               [Actual Line-Item Credit Less Debit@Act Fx Rate PY],
			      [Actual Subtotal Credit Less Debit@Act Fx Rate PY],
			            [Actual Other PY],           
			            
			           [Actual Divide Credit Less Debit@Act Fx Rate PY],
			        [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 6bf47aae-9e60-41a5-b283-c07eea988014

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 R vs PY' = [View F1 P Act] - [View F1 Q PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: 4a3817ef-e784-45e2-a0c4-705248e895aa

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 S vs PY, %' = DIVIDE( [View F1 R vs PY], [View F1 P Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall
		lineageTag: ed646a62-0bf9-4278-8c69-d7f83c8fb13b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 Format MTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View F1 C vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall\Formatting
		lineageTag: a5cd1f9f-ea1d-4ab7-95e4-cd0b940834fb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 Format QTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View F1 H vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall\Formatting
		lineageTag: 7c02cd03-cf4e-4e11-8da6-fac377f60b08

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 Format YTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View F1 m vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall\Formatting
		lineageTag: 97e3e50f-a1e1-46a0-aec6-86b5d7598af1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F1 Format FY' = ```
			 // subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View F1 r vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F1: Overall\Formatting
		lineageTag: e48f4db1-8ab6-4005-be05-2edba674ee51

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@py Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: bf30f5e1-1d35-4187-80ef-5b6ae2d591ca

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 B PY' = ```
			COALESCE(
			           [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD],
			  [Actual Subtotal Credit Less Debit@Act Fx Rate PMTD],
			        [Actual Other PMTD],           
			        
			       [Actual Divide Credit Less Debit@Act Fx Rate PMTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: d29a537d-bbb2-434b-9afd-c4fb18d27039

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 C vs PY' = [View F2 A Act] - [View F2 B PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 57792194-2588-4ff5-b4e4-b19b3c65d444

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 D vs PY, %' = DIVIDE( [View F2 C vs PY], [View F2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 76b8a141-0b5e-4ec2-acf0-f53b90a9571b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: af4d287c-ff40-4aba-af28-58d6d868338e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 F Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@py Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: c0c3a1b2-ba67-4a2a-8924-8c3da0942402

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 G PY' =
			COALESCE(
			            [Actual Line-Item Credit Less Debit@act Fx Rate PQTD],
			            [Actual Subtotal Credit Less Debit@act Fx Rate PQTD],
			            [Actual Other PQTD],
			            [Actual Divide Credit Less Debit@act Fx Rate PQTD],
			        [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 392fd266-a8b9-418b-8384-9be6bb15b6cb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 H vs PY' = [View F2 f Act] - [View F2 g PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 549e743b-9790-42e3-8f47-786210db76a4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 I vs PY, %' = DIVIDE( [View F2 H vs PY], [View F2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: a8b77005-46f9-40da-a3b1-51875fd3ff19

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 9297b657-7c24-4272-92ac-89abe1da0d78

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 K Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@py Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 39a476ed-ba41-427a-9772-85392b876787

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 L PY' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate PYTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate PYTD],
			        [Actual Other PYTD],
			        [Actual Divide Credit Less Debit@act Fx Rate PYTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 345be6a8-74b4-4044-a17c-b4e3c44795ff

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 M vs PY' = [View F2 k Act] - [View F2 l PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: f03ebce2-0348-427c-adb4-73430c79bf1c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 N vs PY, %' = DIVIDE( [View F2 C vs PY], [View F2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 7359bc39-dfe4-41cd-89fd-e9b7019db3d6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 O' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 4381c42a-410a-41bd-a42e-4716a90e5b54

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 P Act' =
			COALESCE(
			    [Actual Line-Item Credit Less Debit@py Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			       [Actual Subtotal Credit Less Debit@py Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			        [Actual Other YTD],
			       [Actual Divide Credit Less Debit@py Fx Rate YTD + Fcst TD Credit Less Debit YTG] ,
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 8f1b924e-0b49-4742-8642-43d4a9beea8b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 Q PY' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate PY] ,
			           [Actual Subtotal Credit Less Debit@act Fx Rate PY] ,
			            [Actual Other PY],
			           [Actual Divide Credit Less Debit@act Fx Rate PY] ,
			        [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 72ad4649-d633-498b-a7bd-8371ea17375c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 R vs PY' = [View F2 P Act] - [View F2 Q PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: bba93b14-a96d-4b70-8cfd-c4d496375547

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 S vs PY, %' = DIVIDE( [View F2 R vs PY], [View F2 P Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying
		lineageTag: 296770c7-772c-4f38-a125-e022f02f37b8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 Format MTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View F2 C vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying\Formatting
		lineageTag: 2a222cb0-2263-4951-81ed-4d697b8ec952

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 Format QTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View F2 H vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying\Formatting
		lineageTag: 966c93ac-a991-40c5-8f8d-10b9f29f1b87

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 Format YTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View F2 m vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying\Formatting
		lineageTag: 158c0b9e-b20f-4314-8692-4dd515974f23

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F2 Format FY' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View F2 r vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F2: Underlying\Formatting
		lineageTag: 020bbe7e-a54d-40d5-89dc-80c7ec8bb702

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 A Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: b36e07bc-7e57-4725-a197-f205fff5b902

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 B Act @py fx' = ```
			COALESCE(
			 
			        [Actual Line-Item Credit Less Debit@py Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@py Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 6b4932ae-6121-4912-bec6-a37da23e46ea

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 C vs Py' = [View F3 A Act @act fx] - [View F3 B Act @py fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: e313b912-fcf6-4815-baa7-1ae25be8535d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 D vs Py, %' = DIVIDE( [View F3 C vs Py], [View F3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 9631e0ab-2b91-4c91-a19e-24ab06d76d36

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 366121e7-623d-4f67-88d6-f73501286f2f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 F Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 3b1f7ec4-3fc7-419d-bf8b-82ec0be9e207

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 G Act @py fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@py Fx Rate QTD],
			    [Blank rows] )* [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 3b90fcff-1233-437b-b168-355e435f6ea6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 H vs Py' = [View F3 F Act @act fx] - [View F3 G Act @py fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 4cd81153-b0a8-4fa7-9052-1d17bccf3dda

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 I vs Py, %' = DIVIDE( [View F3 C vs Py], [View F3 F Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 94ac1050-8329-4160-8695-5f40be0ef051

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: ada50342-f138-40c0-99ec-ad733b13ef9b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 K Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 75578776-bfe6-4ebe-95bc-18a4b3391519

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 L Act @py fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@py Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: e4ce220e-268f-4602-925a-92681e608f36

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 M vs Py' = [View F3 K Act @act fx] - [View F3 L Act @py fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 4ed64b40-58a4-4510-8872-3186519d1c1c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 N vs py, %' = DIVIDE( [View F3 C vs Py], [View F3 K Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx
		lineageTag: 97e7cff7-0a83-4593-9ece-9dfbfc0d0bd9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 Format MTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View F3 C vs Py] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx\Formatting
		lineageTag: f1c1ff0b-252e-4074-b8fe-2bf26dab5be5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 Format QTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View F3 H vs Py] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx\Formatting
		lineageTag: 33e18b08-9ef0-489f-8435-225be9c2d5d0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View F3 Format YTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View F3 m vs Py] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View F: FY Fcst 1 vs PY\View F3: Fx\Formatting
		lineageTag: d0574b90-451e-401c-97b9-b33273419f99

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 7e393f40-88e4-4ac2-a392-88e0438d944d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 B PY' = ```
			COALESCE(
			               [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD],
			      [Actual Subtotal Credit Less Debit@Act Fx Rate PMTD],
			            [Actual Other PMTD],           
			            
			           [Actual Divide Credit Less Debit@Act Fx Rate PMTD],
			        [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: f9876d74-b742-4adf-b4d1-e063aabe43bf

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 C vs PY' = [View G1 A Act] - [View G1 B PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 14cc399b-5236-49c6-b39b-a19e8aef61a2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 D vs PY, %' = DIVIDE( [View G1 C vs PY], [View G1 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 1ea438ed-f7d0-420a-8296-be4e097d5a4a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 4f79a9c9-a70a-4cab-a6d3-1f3b22a81138

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 F Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 2a76011e-a667-418b-90ec-5df02697c01b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 G PY' = ```
			COALESCE(
			               [Actual Line-Item Credit Less Debit@Act Fx Rate PQTD],
			      [Actual Subtotal Credit Less Debit@Act Fx Rate PQTD],
			            [Actual Other PQTD],           
			            
			           [Actual Divide Credit Less Debit@Act Fx Rate PQTD],
			        [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 44742520-7556-4ad4-9b81-91a1aea4945c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 H vs PY' = [View G1 F Act] - [View G1 G PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 22063716-962a-449c-bffc-f747a1fac4fe

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 I vs PY, %' = DIVIDE( [View G1 H vs PY], [View G1 F Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: f53c16af-ab04-4aff-9c94-332abd17301d

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 408670c0-375d-443d-b954-5284d9dcc392

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 K Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@Act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: be768605-922b-43b8-94b8-2e80526a8bf3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 L PY' = ```
			COALESCE(
			               [Actual Line-Item Credit Less Debit@Act Fx Rate PYTD],
			      [Actual Subtotal Credit Less Debit@Act Fx Rate PYTD],
			            [Actual Other pYTD],           
			            
			           [Actual Divide Credit Less Debit@Act Fx Rate PYTD],
			        [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 4fb060da-c32f-4bf8-9c14-c0a0304f8288

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 M vs PY' = [View G1 K Act] - [View G1 l PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 115fa148-f590-4b33-909e-61815d0216de

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 N vs PY, %' = DIVIDE( [View G1 M vs PY], [View G1 K Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 3a3011af-03d5-4542-a69b-6c3df4443db0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 O' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: fef2741f-fef0-4a53-8a12-0c44cf4f59cb

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 P Act' =
			COALESCE(
			    [Actual Line-Item Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			       [Actual Subtotal Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			        [Actual Other YTD],
			       [Actual Divide Credit Less Debit@Act Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 3bfa0772-69a4-47b2-9ea6-c44f4c6a5037

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 Q PY' = ```
			COALESCE(
			               [Actual Line-Item Credit Less Debit@Act Fx Rate PY],
			      [Actual Subtotal Credit Less Debit@Act Fx Rate PY],
			            [Actual Other PY],           
			            
			           [Actual Divide Credit Less Debit@Act Fx Rate PY],
			        [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: feda5bb8-a5dd-4457-b50d-a328266fefa6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 R vs PY' = [View G1 P Act] - [View G1 Q PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 6e9d705a-717c-4d18-ba9e-a223fb3937fd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 S vs PY, %' = DIVIDE( [View G1 R vs PY], [View G1 P Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall
		lineageTag: 3cf6c41b-d5e6-4e07-9737-7e9d17c09873

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 Format MTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View G1 C vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall\Formatting
		lineageTag: 90e8d09d-448d-4b9a-81d1-2009679dab41

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 Format QTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View G1 H vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall\Formatting
		lineageTag: f69e0725-81cc-42af-b479-62bdfe5ddd79

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 Format YTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View G1 m vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall\Formatting
		lineageTag: 022c9749-004a-4023-89c7-4fc678a7af4b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G1 Format FY' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View G1 r vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G1: Overall\Formatting
		lineageTag: 246e7be9-6b6c-497d-87c5-a3e5c2fcc227

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 A Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@py Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: c86224ec-d28d-47ba-b607-40240bbd9641

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 B PY' = ```
			COALESCE(
			           [Actual Line-Item Credit Less Debit@Act Fx Rate PMTD],
			  [Actual Subtotal Credit Less Debit@Act Fx Rate PMTD],
			        [Actual Other PMTD],           
			        
			       [Actual Divide Credit Less Debit@Act Fx Rate PMTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 15bbfc90-259e-4f41-9c54-0b652c398a7a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 C vs PY' = [View G2 A Act] - [View G2 B PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: a2985812-f960-4e19-bfcc-1365443d14c1

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 D vs PY, %' = DIVIDE( [View G2 C vs PY], [View G2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: ad9b58b1-4e11-4f27-9c8a-a391576295b6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 1133ffa8-cace-4f3b-b187-f19ee64125ee

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 F Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@py Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 6f278449-db96-4eb8-832b-1e5f76f354e9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 G PY' =
			COALESCE(
			            [Actual Line-Item Credit Less Debit@act Fx Rate PQTD],
			            [Actual Subtotal Credit Less Debit@act Fx Rate PQTD],
			            [Actual Other PQTD],
			            [Actual Divide Credit Less Debit@act Fx Rate PQTD],
			        [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 3698605d-0348-4f9b-a519-816e871fd0c8

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 H vs PY' = [View G2 f Act] - [View G2 g PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: e2f28b5e-4879-47e6-b911-de7ae5a60364

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 I vs PY, %' = DIVIDE( [View G2 H vs PY], [View G2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 5e51c9a0-73a1-44b7-b736-91e85621506c

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 727e5cc7-f6e9-41a6-b61b-69e9fff3f5f2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 K Act' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@py Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 15c30754-9404-4147-91e4-85d94510cc45

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 L PY' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate PYTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate PYTD],
			        [Actual Other PYTD],
			        [Actual Divide Credit Less Debit@act Fx Rate PYTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 748f55d3-35c9-4802-a604-deec94813fe3

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 M vs PY' = [View G2 k Act] - [View G2 l PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 56150cd0-6b66-4f22-a349-13878b79fe71

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 N vs PY, %' = DIVIDE( [View G2 C vs PY], [View G2 A Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 03a963e8-73aa-4a59-8512-eb9de7749740

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 O' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 266f6e3d-b8a4-459f-95bb-2e809c3bad6e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 P Act' =
			COALESCE(
			    [Actual Line-Item Credit Less Debit@py Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			       [Actual Subtotal Credit Less Debit@py Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			        [Actual Other YTD],
			       [Actual Divide Credit Less Debit@py Fx Rate YTD + Fcst BU Credit Less Debit YTG] ,
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 45342277-4384-4b93-8a07-7f6532968d05

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 Q PY' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate PY] ,
			           [Actual Subtotal Credit Less Debit@act Fx Rate PY] ,
			            [Actual Other PY],
			           [Actual Divide Credit Less Debit@act Fx Rate PY] ,
			        [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 1673dad3-1e8e-4e9f-95e8-dd05e22974b9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 R vs PY' = [View G2 P Act] - [View G2 Q PY]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: 16f189a6-0c16-4e41-9bd8-db63e4426bc7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 S vs PY, %' = DIVIDE( [View G2 R vs PY], [View G2 P Act] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying
		lineageTag: aad15def-b925-4f36-83bd-44a9890de89b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 Format MTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View G2 C vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying\Formatting
		lineageTag: d5dd0886-d25c-4d64-bab5-a9540a7308f5

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 Format QTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View G2 H vs PY] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying\Formatting
		lineageTag: 0602a36b-e3f2-4fcd-b387-513e8c8c6608

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 Format YTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View G2 m vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying\Formatting
		lineageTag: 0228a63f-e8f0-4f94-9f02-0787f03dc1ca

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G2 Format FY' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View G2 r vs PY] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G2: Underlying\Formatting
		lineageTag: 6ee6a02e-df18-41c2-8a8b-7bab62d973ae

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 A Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@act Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: dbef7db6-166a-409a-9ce3-d22090967a00

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 B Act @py fx' = ```
			COALESCE(
			 
			        [Actual Line-Item Credit Less Debit@py Fx Rate MTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate MTD],
			        [Actual Other MTD],
			        [Actual Divide Credit Less Debit@py Fx Rate MTD],
			    [Blank rows] ) * [Show Value]
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: 9ec24e56-5d25-47f2-8b88-4eb0fd611186

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 C vs Py' = [View G3 A Act @act fx] - [View G3 B Act @py fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: acb9b95d-73b4-4616-ab4f-e7161bdbac79

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 D vs Py, %' = DIVIDE( [View G3 C vs Py], [View G3 A Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: 0bc5ba8c-8bf5-4059-9539-7c5a3563f263

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 E' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: c42824e8-c954-40d2-9bd0-9ceac1e64c57

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 F Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@act Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: f433f5cd-3713-4066-92a0-2e4327bb0f84

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 G Act @py fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate QTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate QTD],
			        [Actual Other QTD],
			        [Actual Divide Credit Less Debit@py Fx Rate QTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: 30c32300-3529-41c8-a73b-57a6dfbaa3c7

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 H vs Py' = [View G3 F Act @act fx] - [View G3 G Act @py fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: c4e0d745-ced0-4801-b55f-6bf8c51a9f97

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 I vs Py, %' = DIVIDE( [View G3 C vs Py], [View G3 F Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: c9db4d23-1bc6-4f01-b789-eac8fe6abafd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 J' = [Blank Column]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: 438d96ca-bd30-4f10-8af3-3c02a380e3dd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 K Act @act fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@act Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@act Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: 10244951-4145-4bc3-90e1-11fd68c3cbb0

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 L Act @py fx' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@py Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@py Fx Rate YTD],
			        [Actual Other YTD],
			        [Actual Divide Credit Less Debit@py Fx Rate YTD],
			    [Blank rows] ) * [Show Value]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: 1c79a5b9-ca62-4660-b7ad-87915f82827b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 M vs Py' = [View G3 K Act @act fx] - [View G3 L Act @py fx]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: cb029770-e5ea-445f-97ee-e9fe36f88c84

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 N vs PY, %' = DIVIDE( [View G3 C vs Py], [View G3 K Act @act fx] ) * [Show Perc]
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx
		lineageTag: e20cdb46-0ddf-4c2d-9bfe-0b4e7bfa1d33

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 Format MTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View G3 C vs Py] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx\Formatting
		lineageTag: 1c349d08-d5b3-46a8-8e61-19928a88503b

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 Format QTD' = ```
			// subtotal
			        VAR NCLD_filter_context_calculated_table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			            )
			        VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			    
			        //percentage
			        VAR numeratormax = MAX( Layout[Divide_Numerator] )
			        VAR Pct_Table =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= numeratormax,
			                Layout[Income_Statement_Key] <= numeratormax
			            )
			        VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			        VAR NCLD_filter_context_calculated_table_Pct =
			            CALCULATETABLE(
			                Layout,
			                REMOVEFILTERS( Layout ),
			                Layout[Income_Statement_Key] >= subtotalfrom,
			                Layout[Income_Statement_Key] <= subtotalto
			            )
			        VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			    
			    
			    
			    
			        // indicatpr
			        VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			VAR varianceadj =  [View G3 H vs Py] * indicator 
			
			VAR result = 
			SWITCH(
			    TRUE(),
			    varianceadj > 0, [green],
			    varianceadj < 0, [Red],
			    [Gray]
			    
			)
			       
			    RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx\Formatting
		lineageTag: fcf7719c-fc48-4dd2-a83d-93bf5bed052f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'View G3 Format YTD' = ```
			   // subtotal
			            VAR NCLD_filter_context_calculated_table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= MIN( Layout[Subtotal_From] ),
			                    Layout[Income_Statement_Key] <= MIN( Layout[Subtotal_To] )
			                )
			            VAR indicatorsubtotal = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table )
			        
			            //percentage
			            VAR numeratormax = MAX( Layout[Divide_Numerator] )
			            VAR Pct_Table =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= numeratormax,
			                    Layout[Income_Statement_Key] <= numeratormax
			                )
			            VAR subtotalfrom = CALCULATE( MAX( Layout[Subtotal_From] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR subtotalto = CALCULATE( MAX( Layout[Subtotal_To] ), REMOVEFILTERS( Layout ), Pct_Table )
			            VAR NCLD_filter_context_calculated_table_Pct =
			                CALCULATETABLE(
			                    Layout,
			                    REMOVEFILTERS( Layout ),
			                    Layout[Income_Statement_Key] >= subtotalfrom,
			                    Layout[Income_Statement_Key] <= subtotalto
			                )
			            VAR indicatorpct = CALCULATE( [Net Credit Less Debit Indicator], NCLD_filter_context_calculated_table_Pct )
			        
			        
			        
			        
			            // indicatpr
			            VAR indicator = COALESCE( [Net Credit Less Debit Indicator], indicatorsubtotal, indicatorpct )
			    VAR varianceadj =  [View G3 m vs Py] * indicator 
			    
			    VAR result = 
			    SWITCH(
			        TRUE(),
			        varianceadj > 0, [green],
			        varianceadj < 0, [Red],
			        [Gray]
			        
			    )
			           
			        RETURN result
			```
		isHidden
		displayFolder: Step 08: Field Paramaters\View G: FY Fcst 2 vs PY\View G3: Fx\Formatting
		lineageTag: a1c4631a-68a0-438c-93a8-8c2b21c2a79e

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other PMTD' = CALCULATE([Actual Other@Base Caculations], 'Effective Date'[PMTD] = 1)
		isHidden
		displayFolder: Step 05: Other\2_Comparison\Act + Fcst\Prior Month To Date (PMTD)
		lineageTag: 8f0e181f-4520-4aa3-9e7e-7085f46095d2

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other PQTD' = CALCULATE([Actual Other@Base Caculations TD], 'Effective Date'[PQTD] = 1)
		isHidden
		displayFolder: Step 05: Other\2_Comparison\Act + Fcst\Prior Quarter To Date (PQTD)
		lineageTag: 186b2d80-cc5c-46d6-bbfc-7748076646c4

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Other@Base Caculations TD' = ```
			VAR Isaccountordatefiltered = IF( OR( ISFILTERED( Account ), ISFILTERED( 'Effective Date'[Fiscal Date] ) ), BLANK( ), 1 )
			
			
			
			    // Part 2: Determines the layout calculation type
			
			    VAR SelectedCalcualtionType = SELECTEDVALUE( Layout[Calculation_type] )
			
			
			
			    // Part 3: Determines which Time Period selected
			
			    VAR SelectedTimePeriod =
			        SELECTEDVALUE(
			            'Effective Date'[Fiscal Year-Period],
			            SELECTEDVALUE(
			                'Effective Date'[Fiscal Year-Quarter],
			                CONVERT( SELECTEDVALUE( 'Effective Date'[Fiscal Year] ), STRING )
			            )
			        ) & "-TD"
			
			
			
			    // Part 4: Filter the other non-generel ledger information table down to calculation type  // and the time period in scope
			
			    VAR CalculateTableOtherNonGeneralLedgerInformation =
			        CALCULATETABLE(
			            'Other Non General Ledger Information',
			            'Other Non General Ledger Information'[Calculation type] = SelectedCalcualtionType,
			            'Other Non General Ledger Information'[Time period] = SelectedTimePeriod
			        ) 
			
			
			
			    // Part 5: Sum the value of the filtered table in part 4 and return blank if The accounts table is in scope
			
			    VAR result =
			        CALCULATE( SUM( 'Other Non General Ledger Information'[Value] ), CalculateTableOtherNonGeneralLedgerInformation )
			            * Isaccountordatefiltered
			
			
			
			    // Part 6: Return to result
			
			    RETURN
			        result
			```
		isHidden
		displayFolder: Step 05: Other\_Base calculations
		lineageTag: 3eca5abb-ad28-4ee7-ba25-daa2869d9d49

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Actual Currency' = [Actual Line-Item Credit Less Debit@Act Fx Rate YTD]
		isHidden
		displayFolder: Step 09: Currency Impact
		lineageTag: 91ee2649-affb-4b25-9aa9-b9f37b76b05a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "#,##0,;(#,##0,);-" )

		changedProperty = IsHidden

	measure 'Plan Currency' = [Actual Line-Item Credit Less Debit@Plan Fx Rate YTD]
		isHidden
		displayFolder: Step 09: Currency Impact
		lineageTag: daee4279-3dfa-47d7-a73b-1790190bc897

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "#,##0,;(#,##0,);-" )

		changedProperty = IsHidden

	measure 'Var Currency' = [Actual Currency] - [Plan Currency]
		isHidden
		displayFolder: Step 09: Currency Impact
		lineageTag: 423b93f4-20fa-42d1-a97f-dde9cb7536d9

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Abs], "+#,##0,;-#,##0,;-" )

		changedProperty = IsHidden

	measure 'Var, % Currency' = DIVIDE( [Var Currency], [Actual Currency] )
		isHidden
		displayFolder: Step 09: Currency Impact
		lineageTag: 9c6fd25d-1f53-4408-a712-1495242844bd

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Variance_Per], "+0.00%;-0.00%;-" )

		changedProperty = IsHidden

	measure 'Var Currency Format' =
			SWITCH(
			        TRUE( ),
			        [Var Currency] > 0, [Green],
			        [Var Currency] < 0, [Red],
			        [Gray]
			    )
		isHidden
		displayFolder: Step 09: Currency Impact
		lineageTag: f17425e4-eb7b-4d20-b4ee-5ae2dc2903c8

		changedProperty = IsHidden

	measure 'Show Value Forecast BU' = ```
			VAR showvalues = values(Layout[Show_Values])
			    VAR isnotfilteredaccount = ISFILTERED(Account) = FALSE()
			    //VAR isnotfilteredbusinessunit = isfiltered('Business Unit') = false()
			   // var isnotfilteredlegalentity = countrows('Legal Entity') = CALCULATE(countrows('Legal Entity'), REMOVEFILTERS('Legal Entity'))
			    var hasoneshowvalue = hasonevalue(Layout[Show_Values])
			    
			    var result = 
			        SWITCH(
			            TRUE(),     
			            isnotfilteredaccount    &&hasoneshowvalue , showvalues,
			            
			            BLANK()
			        
			            
			        )        
			    return  result
			```
		isHidden
		displayFolder: Step 07: Show Values and Blanks
		lineageTag: ded9d26f-3493-47db-a2f8-ecdf196cf05a

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Line Name Background' = ```
			VAR CalcType = SELECTEDVALUE(Layout[Calculation_type]) 
			VAR Subtotals = CalcType  = "Subtotal"
			VAR Divides = CalcType  = "Divide"
			
			VAR result =
			    
			    SWITCH(
			        TRUE(),
			        Subtotals, [Gray],
			        Divides, [Gray]
			        
			    )
			    
			RETURN result
			```
		isHidden
		lineageTag: 846c47bf-77c1-475b-b8b1-80b4cc8f13b6

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Line Name Font' = ```
			VAR CalcType = SELECTEDVALUE(Layout[Calculation_type]) 
			VAR Subtotals = CalcType  = "Subtotal"
			VAR Divides = CalcType  = "Divide"
			
			VAR result =
			    
			    SWITCH(
			        TRUE(),
			        Subtotals, [Blue],
			        Divides, [Blue],
			        [Medium Gray]
			        
			    )
			    
			RETURN result
			```
		isHidden
		lineageTag: da9db181-6145-4784-9730-226640cc743f

		formatStringDefinition = SELECTEDVALUE( Layout[Format_String_Default], "0;0-0;;@" )

		changedProperty = IsHidden

	measure 'Document number actuals' =
			COALESCE(
			        [Actual Line-Item Credit Less Debit@Act Fx Rate YTD],
			        [Actual Subtotal Credit Less Debit@Act Fx Rate YTD]
			  )
		formatString: $#,###
		isHidden
		lineageTag: 0f6717ce-d57f-41f9-8fbc-122729b9a4ab

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	partition Measures_Hidden = m
		mode: import
		queryGroup: Measures
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

